services:
  api:
    image: patricklaviola/giveaway-api:latest
    build:
      context: ./api
    env_file:
      - ./api/.env
    ports:
      - 4000:4000
    restart: unless-stopped
  web:
    image: patricklaviola/giveaway-web:latest
    depends_on:
      - api
    build:
      context: ./ui
    env_file:
      - ./ui/.env.production
    ports:
      - 3000:3000
    restart: unless-stopped
