import { NbaEvent } from "./types";

const events: NbaEvent[] = [
  {
    league: "gleaguenba",
    teamName: "spurs",
    eventName:
      "20th Anniversary Austin Spurs Jersey - 1st 1,000 Fans to purchase a ticket ",
    rawName:
      "20th Anniversary Austin Spurs Jersey - 1st 1,000 Fans to purchase a ticket ",
    matchup: "Birmingham Squadron",
    startDate: "2025-11-09",
    endDate: "2025-11-09",
    description: " on November 9, 2025 at 3:00 p.m.",
    timeAndZone: "3:00PM CST",
    location: "H-E-B Center at Cedar Center",
    offerURL: "https://austin.gleague.nba.com/theme-nights",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "spurs",
    eventName: "Winning Weekday ",
    rawName: "Winning Weekday ",
    matchup: "Osceola Magic",
    startDate: "2025-11-19",
    endDate: "2025-11-19",
    description: " on November 19, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "H-E-B Center at Cedar Center",
    offerURL: "https://austin.gleague.nba.com/theme-nights",
    dayOfWeek: "wednesday",
  },

  {
    league: "gleaguenba",
    teamName: "spurs",
    eventName: "Toros $10 T-shirt Pack ",
    rawName: "Toros $10 T-shirt Pack ",
    matchup: "Osceola Magic",
    startDate: "2025-11-20",
    endDate: "2025-11-20",
    description: " on November 20, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "H-E-B Center at Cedar Center",
    offerURL: "https://austin.gleague.nba.com/theme-nights",
    dayOfWeek: "thursday",
  },

  {
    league: "gleaguenba",
    teamName: "spurs",
    eventName: "DC Super Heroes Night - Super Hero Maks - 1st 1,000 fans",
    rawName: "DC Super Heroes Night - Super Hero Maks - 1st 1,000 fans",
    matchup: "Rio Grande Valley Vipers",
    startDate: "2025-11-23",
    endDate: "2025-11-23",
    description: " on November 23, 2025 at 3:00 p.m.",
    timeAndZone: "3:00PM CST",
    location: "H-E-B Center at Cedar Center",
    offerURL: "https://austin.gleague.nba.com/theme-nights",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "spurs",
    eventName: "Winning Weekdays",
    rawName: "Winning Weekdays",
    matchup: "Rio Grande Valley Vipers",
    startDate: "2025-11-24",
    endDate: "2025-11-24",
    description: " on November 24, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "H-E-B Center at Cedar Center",
    offerURL: "https://austin.gleague.nba.com/theme-nights",
    dayOfWeek: "monday",
  },

  {
    league: "gleaguenba",
    teamName: "spurs",
    eventName: "Harry Potter Hat Ticket Package ",
    rawName: "Harry Potter Hat Ticket Package ",
    matchup: "Mexico City Capitanes",
    startDate: "2025-12-27",
    endDate: "2025-12-27",
    description: " on December 27, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "H-E-B Center at Cedar Center",
    offerURL: "https://austin.gleague.nba.com/theme-nights",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "spurs",
    eventName: "Toros $10 T-shirt Pack; $3 Drink Night",
    rawName: "Toros $10 T-shirt Pack; $3 Drink Night",
    matchup: "South Bay Lakers",
    startDate: "2026-01-09",
    endDate: "2026-01-09",
    description: " on January 9, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "H-E-B Center at Cedar Center",
    offerURL: "https://austin.gleague.nba.com/theme-nights",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "spurs",
    eventName: "Riverdragon Shield - 1st 1,000 Fans",
    rawName: "Riverdragon Shield - 1st 1,000 Fans",
    matchup: "South Bay Lakers",
    startDate: "2026-01-10",
    endDate: "2026-01-10",
    description: " on January 10, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "H-E-B Center at Cedar Center",
    offerURL: "https://austin.gleague.nba.com/theme-nights",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "spurs",
    eventName: "Winning Weekday",
    rawName: "Winning Weekday",
    matchup: "Capital City Go-Go",
    startDate: "2026-01-22",
    endDate: "2026-01-22",
    description: " on January 22, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "H-E-B Center at Cedar Center",
    offerURL: "https://austin.gleague.nba.com/theme-nights",
    dayOfWeek: "thursday",
  },

  {
    league: "gleaguenba",
    teamName: "spurs",
    eventName: "Toros $10 T-shirt Pack; $3 Drink Night",
    rawName: "Toros $10 T-shirt Pack; $3 Drink Night",
    matchup: "Capital City Go-Go",
    startDate: "2026-01-23",
    endDate: "2026-01-23",
    description: " on January 23, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "H-E-B Center at Cedar Center",
    offerURL: "https://austin.gleague.nba.com/theme-nights",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "spurs",
    eventName: "Winning Weekday",
    rawName: "Winning Weekday",
    matchup: "Stockton Kings",
    startDate: "2026-01-29",
    endDate: "2026-01-29",
    description: " on January 29, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "H-E-B Center at Cedar Center",
    offerURL: "https://austin.gleague.nba.com/theme-nights",
    dayOfWeek: "thursday",
  },

  {
    league: "gleaguenba",
    teamName: "spurs",
    eventName: "Star Wars Jersey Ticket Package",
    rawName: "Star Wars Jersey Ticket Package",
    matchup: "Memphis Hustle",
    startDate: "2026-02-22",
    endDate: "2026-02-22",
    description: " on February 22, 2026 at 3:00 p.m.",
    timeAndZone: "3:00PM CST",
    location: "H-E-B Center at Cedar Center",
    offerURL: "https://austin.gleague.nba.com/theme-nights",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "spurs",
    eventName: "Express $10 T-Shirt Ticket Package",
    rawName: "Express $10 T-Shirt Ticket Package",
    matchup: "Memphis Hustle",
    startDate: "2026-03-01",
    endDate: "2026-03-01",
    description: " on March 1, 2026 at 3:00 p.m.",
    timeAndZone: "3:00PM CST",
    location: "H-E-B Center at Cedar Center",
    offerURL: "https://austin.gleague.nba.com/theme-nights",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "spurs",
    eventName: "Kids 12 & Under get in Free; Tiara Giveaway - 1st 500 Fans",
    rawName: "Kids 12 & Under get in Free; Tiara Giveaway - 1st 500 Fans",
    matchup: "Stockton Kings",
    startDate: "2026-03-15",
    endDate: "2026-03-15",
    description: " on March 15, 2026 at 3:00 p.m.",
    timeAndZone: "3:00PM CST",
    location: "H-E-B Center at Cedar Center",
    offerURL: "https://austin.gleague.nba.com/theme-nights",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "spurs",
    eventName: "Winning Weekday",
    rawName: "Winning Weekday",
    matchup: "Rip City Remix",
    startDate: "2026-03-25",
    endDate: "2026-03-25",
    description: " on March 25, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "H-E-B Center at Cedar Center",
    offerURL: "https://austin.gleague.nba.com/theme-nights",
    dayOfWeek: "wednesday",
  },

  {
    league: "gleaguenba",
    teamName: "spurs",
    eventName: "Raros Cowboy Hats - 1st 500 Fans",
    rawName: "Raros Cowboy Hats - 1st 500 Fans",
    matchup: "Rip City Remix",
    startDate: "2026-03-27",
    endDate: "2026-03-27",
    description: " on March 27, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "H-E-B Center at Cedar Center",
    offerURL: "https://austin.gleague.nba.com/theme-nights",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "skyhawks",
    eventName: "Opening Night",
    rawName: "Opening Night",
    matchup: "Capital City Go-Go",
    startDate: "2025-11-14",
    endDate: "2025-11-14",
    description: " on November 14, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Gateway Center Arena",
    offerURL:
      "https://cpskyhawks.gleague.nba.com/news/college-park-skyhawks-announce-2025-26-season-schedule",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "skyhawks",
    eventName: "Educator Day",
    rawName: "Educator Day",
    matchup: "Westchester Knicks",
    startDate: "2025-12-03",
    endDate: "2025-12-03",
    description: " on December 3, 2025 at 11:00 a.m.",
    timeAndZone: "11:00AM EST",
    location: "Gateway Center Arena",
    offerURL:
      "https://cpskyhawks.gleague.nba.com/news/college-park-skyhawks-announce-2025-26-season-schedule",
    dayOfWeek: "wednesday",
  },

  {
    league: "gleaguenba",
    teamName: "skyhawks",
    eventName: "Holiday Game",
    rawName: "Holiday Game",
    matchup: "Greensboro Swarm",
    startDate: "2025-12-14",
    endDate: "2025-12-14",
    description: " on December 14, 2025 at 2:00 p.m.",
    timeAndZone: "2:00PM EST",
    location: "Gateway Center Arena",
    offerURL:
      "https://cpskyhawks.gleague.nba.com/news/college-park-skyhawks-announce-2025-26-season-schedule",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "skyhawks",
    eventName: "Celebrating Black History",
    rawName: "Celebrating Black History",
    matchup: "Rip City Remix",
    startDate: "2026-02-07",
    endDate: "2026-02-07",
    description: " on February 7, 2026 at 3:00 p.m.",
    timeAndZone: "3:00PM EST",
    location: "Gateway Center Arena",
    offerURL:
      "https://cpskyhawks.gleague.nba.com/news/college-park-skyhawks-announce-2025-26-season-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "skyhawks",
    eventName: "Fan Appreciation Night",
    rawName: "Fan Appreciation Night",
    matchup: "Osceola Magic",
    startDate: "2026-03-25",
    endDate: "2026-03-25",
    description: " on March 25, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Gateway Center Arena",
    offerURL:
      "https://cpskyhawks.gleague.nba.com/news/college-park-skyhawks-announce-2025-26-season-schedule",
    dayOfWeek: "wednesday",
  },

  {
    league: "gleaguenba",
    teamName: "squadron",
    eventName: "Opening Night Squadron Tour T-Shirt",
    rawName: "Opening Night Squadron Tour T-Shirt",
    matchup: "Austin Spurs",
    startDate: "2025-11-07",
    endDate: "2025-11-07",
    description: " on November 7, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Legacy Arena",
    offerURL: "https://birmingham.gleague.nba.com/2024-25-single-game-tickets",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "squadron",
    eventName: "Rubik's Cube",
    rawName: "Rubik's Cube",
    matchup: "Memphis Hustle",
    startDate: "2025-12-03",
    endDate: "2025-12-03",
    description: " on December 3, 2025 at 11:00 p.m.",
    timeAndZone: "11:00AM EST",
    location: "Legacy Arena",
    offerURL: "https://birmingham.gleague.nba.com/2024-25-single-game-tickets",
    dayOfWeek: "wednesday",
  },

  {
    league: "gleaguenba",
    teamName: "squadron",
    eventName: "Commander Bobblehead",
    rawName: "Commander Bobblehead",
    matchup: "Memphis Hustle",
    startDate: "2025-12-05",
    endDate: "2025-12-05",
    description: " on December 5, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Legacy Arena",
    offerURL: "https://birmingham.gleague.nba.com/2024-25-single-game-tickets",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "squadron",
    eventName: "Military Wall Flag",
    rawName: "Military Wall Flag",
    matchup: "Texas Legends",
    startDate: "2025-12-07",
    endDate: "2025-12-07",
    description: " on December 7, 2025 at 3:00 p.m.",
    timeAndZone: "3:00PM EST",
    location: "Legacy Arena",
    offerURL: "https://birmingham.gleague.nba.com/2024-25-single-game-tickets",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "squadron",
    eventName: "TBA Giveaway",
    rawName: "TBA Giveaway",
    matchup: "Texas Legends",
    startDate: "2025-12-09",
    endDate: "2025-12-09",
    description: " on December 9, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Legacy Arena",
    offerURL: "https://birmingham.gleague.nba.com/2024-25-single-game-tickets",
    dayOfWeek: "tuesday",
  },

  {
    league: "gleaguenba",
    teamName: "squadron",
    eventName: "TBA Giveaway",
    rawName: "TBA Giveaway",
    matchup: "Rio Grande Valley Vipers",
    startDate: "2025-12-14",
    endDate: "2025-12-14",
    description: " on December 14, 2025 at 3:00 p.m.",
    timeAndZone: "3:00PM EST",
    location: "Legacy Arena",
    offerURL: "https://birmingham.gleague.nba.com/2024-25-single-game-tickets",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "squadron",
    eventName: "TBA Giveaway",
    rawName: "TBA Giveaway",
    matchup: "Osceola Magic",
    startDate: "2026-01-08",
    endDate: "2026-01-08",
    description: " on January 8, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Legacy Arena",
    offerURL: "https://birmingham.gleague.nba.com/2024-25-single-game-tickets",
    dayOfWeek: "thursday",
  },

  {
    league: "gleaguenba",
    teamName: "squadron",
    eventName: "TBA Giveaway",
    rawName: "TBA Giveaway",
    matchup: "Osceola Magic",
    startDate: "2026-01-10",
    endDate: "2026-01-10",
    description: " on January 10, 2026 at 6:00 p.m.",
    timeAndZone: "6:00PM EST",
    location: "Legacy Arena",
    offerURL: "https://birmingham.gleague.nba.com/2024-25-single-game-tickets",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "squadron",
    eventName: "TBA Giveaway",
    rawName: "TBA Giveaway",
    matchup: "Raptors 905",
    startDate: "2026-01-11",
    endDate: "2026-01-11",
    description: " on January 11, 2026 at 5:00 p.m.",
    timeAndZone: "5:00PM EST",
    location: "Legacy Arena",
    offerURL: "https://birmingham.gleague.nba.com/2024-25-single-game-tickets",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "squadron",
    eventName: "Trading Cards",
    rawName: "Trading Cards",
    matchup: "Raptors 905",
    startDate: "2026-01-13",
    endDate: "2026-01-13",
    description: " on January 13, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Legacy Arena",
    offerURL: "https://birmingham.gleague.nba.com/2024-25-single-game-tickets",
    dayOfWeek: "tuesday",
  },

  {
    league: "gleaguenba",
    teamName: "squadron",
    eventName: "Lab Coat Koozie",
    rawName: "Lab Coat Koozie",
    matchup: "Motor City Cruise",
    startDate: "2026-01-15",
    endDate: "2026-01-15",
    description: " on January 15, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Legacy Arena",
    offerURL: "https://birmingham.gleague.nba.com/2024-25-single-game-tickets",
    dayOfWeek: "thursday",
  },

  {
    league: "gleaguenba",
    teamName: "squadron",
    eventName: "205 Night T-Shirt",
    rawName: "205 Night T-Shirt",
    matchup: "Motor City Cruise",
    startDate: "2026-01-17",
    endDate: "2026-01-17",
    description: " on January 17, 2026 at 6:00 p.m.",
    timeAndZone: "6:00PM EST",
    location: "Legacy Arena",
    offerURL: "https://birmingham.gleague.nba.com/2024-25-single-game-tickets",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "squadron",
    eventName: "TBA",
    rawName: "TBA",
    matchup: "Greensboro Swarm",
    startDate: "2026-01-19",
    endDate: "2026-01-19",
    description: " on January 19, 2026 at 1:00 p.m.",
    timeAndZone: "1:00PM EST",
    location: "Legacy Arena",
    offerURL: "https://birmingham.gleague.nba.com/2024-25-single-game-tickets",
    dayOfWeek: "monday",
  },

  {
    league: "gleaguenba",
    teamName: "squadron",
    eventName: "TBA",
    rawName: "TBA",
    matchup: "Cleveland Charge",
    startDate: "2026-01-22",
    endDate: "2026-01-22",
    description: " on January 22, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Legacy Arena",
    offerURL: "https://birmingham.gleague.nba.com/2024-25-single-game-tickets",
    dayOfWeek: "thursday",
  },

  {
    league: "gleaguenba",
    teamName: "squadron",
    eventName: "Pop-It Toy / Sensory Bag",
    rawName: "Pop-It Toy / Sensory Bag",
    matchup: "Cleveland Charge",
    startDate: "2026-01-24",
    endDate: "2026-01-24",
    description: " on January 24, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Legacy Arena",
    offerURL: "https://birmingham.gleague.nba.com/2024-25-single-game-tickets",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "squadron",
    eventName: "TBA",
    rawName: "TBA",
    matchup: "Sioux Falls Skyforce",
    startDate: "2026-01-28",
    endDate: "2026-01-28",
    description: " on January 28, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Legacy Arena",
    offerURL: "https://birmingham.gleague.nba.com/2024-25-single-game-tickets",
    dayOfWeek: "wednesday",
  },

  {
    league: "gleaguenba",
    teamName: "squadron",
    eventName: "TBA",
    rawName: "TBA",
    matchup: "Rip City Remix",
    startDate: "2026-02-12",
    endDate: "2026-02-12",
    description: " on February 12, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Legacy Arena",
    offerURL: "https://birmingham.gleague.nba.com/2024-25-single-game-tickets",
    dayOfWeek: "thursday",
  },

  {
    league: "gleaguenba",
    teamName: "squadron",
    eventName: "TBA",
    rawName: "TBA",
    matchup: "Long Island Nets",
    startDate: "2026-02-19",
    endDate: "2026-02-19",
    description: " on February 19, 2026 at 11:00 a.m.",
    timeAndZone: "11:00AM EST",
    location: "Legacy Arena",
    offerURL: "https://birmingham.gleague.nba.com/2024-25-single-game-tickets",
    dayOfWeek: "thursday",
  },

  {
    league: "gleaguenba",
    teamName: "squadron",
    eventName: "TBA",
    rawName: "TBA",
    matchup: "Long Island Nets",
    startDate: "2026-02-20",
    endDate: "2026-02-20",
    description: " on February 20, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Legacy Arena",
    offerURL: "https://birmingham.gleague.nba.com/2024-25-single-game-tickets",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "squadron",
    eventName: "TBA",
    rawName: "TBA",
    matchup: "Maine Celtics",
    startDate: "2026-03-16",
    endDate: "2026-03-16",
    description: " on March 16, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Legacy Arena",
    offerURL: "https://birmingham.gleague.nba.com/2024-25-single-game-tickets",
    dayOfWeek: "monday",
  },

  {
    league: "gleaguenba",
    teamName: "squadron",
    eventName: "TBA",
    rawName: "TBA",
    matchup: "Maine Celtics",
    startDate: "2026-03-17",
    endDate: "2026-03-17",
    description: " on March 17, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Legacy Arena",
    offerURL: "https://birmingham.gleague.nba.com/2024-25-single-game-tickets",
    dayOfWeek: "tuesday",
  },

  {
    league: "gleaguenba",
    teamName: "squadron",
    eventName: "Over Door Hoop",
    rawName: "Over Door Hoop",
    matchup: "Windy City Bulls",
    startDate: "2026-03-22",
    endDate: "2026-03-22",
    description: " on March 22, 2026 at 3:00 p.m.",
    timeAndZone: "3:00PM EST",
    location: "Legacy Arena",
    offerURL: "https://birmingham.gleague.nba.com/2024-25-single-game-tickets",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "squadron",
    eventName: "TBA",
    rawName: "TBA",
    matchup: "Windy City Bulls",
    startDate: "2026-03-24",
    endDate: "2026-03-24",
    description: " on March 24, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Legacy Arena",
    offerURL: "https://birmingham.gleague.nba.com/2024-25-single-game-tickets",
    dayOfWeek: "tuesday",
  },

  {
    league: "gleaguenba",
    teamName: "charge",
    eventName: "Schedule Mini Hoop - 1st 2,000 Fans",
    rawName: "Schedule Mini Hoop - 1st 2,000 Fans",
    matchup: "Wisconsin Herd",
    startDate: "2025-11-14",
    endDate: "2025-11-14",
    description: " on November 14, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Public Auditorium",
    offerURL:
      "https://cleveland.gleague.nba.com/news/cleveland-charge-unveil-2025-26-promotional-schedule",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "charge",
    eventName: "Trading Card Giveaway - 1st 2,000 Fans",
    rawName: "Trading Card Giveaway - 1st 2,000 Fans",
    matchup: "Wisconsin Herd",
    startDate: "2025-11-15",
    endDate: "2025-11-15",
    description: " on November 15, 2025 at 7:30 p.m.",
    timeAndZone: "7:30PM EST",
    location: "Public Auditorium",
    offerURL:
      "https://cleveland.gleague.nba.com/news/cleveland-charge-unveil-2025-26-promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "charge",
    eventName: "Pozzie Puzzle - 1st 1,500 Fans",
    rawName: "Pozzie Puzzle - 1st 1,500 Fans",
    matchup: "Grand Rapids Gold",
    startDate: "2025-11-22",
    endDate: "2025-11-22",
    description: " on November 22, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Public Auditorium",
    offerURL:
      "https://cleveland.gleague.nba.com/news/cleveland-charge-unveil-2025-26-promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "charge",
    eventName: "Charge Hooded Jersey - 1st 1,500 Fans",
    rawName: "Charge Hooded Jersey - 1st 1,500 Fans",
    matchup: "Sioux Falls Skyforce",
    startDate: "2025-12-13",
    endDate: "2025-12-13",
    description: " on December 13, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Public Auditorium",
    offerURL:
      "https://cleveland.gleague.nba.com/news/cleveland-charge-unveil-2025-26-promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "charge",
    eventName: "Pablo Sanchez BobbleCard - 1st 1,500 Fans",
    rawName: "Pablo Sanchez BobbleCard - 1st 1,500 Fans",
    matchup: "Delaware Blue Coats",
    startDate: "2025-12-27",
    endDate: "2025-12-27",
    description: " on December 27, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Public Auditorium",
    offerURL:
      "https://cleveland.gleague.nba.com/news/cleveland-charge-unveil-2025-26-promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "charge",
    eventName: "Classic Cavs Charge Shirt - 1st 1,500 Fans",
    rawName: "Classic Cavs Charge Shirt - 1st 1,500 Fans",
    matchup: "Wisconsin Herd",
    startDate: "2025-12-30",
    endDate: "2025-12-30",
    description: " on December 30, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Public Auditorium",
    offerURL:
      "https://cleveland.gleague.nba.com/news/cleveland-charge-unveil-2025-26-promotional-schedule",
    dayOfWeek: "tuesday",
  },

  {
    league: "gleaguenba",
    teamName: "charge",
    eventName: "Lunch Box & Thermos - 1st 1,500 Fans",
    rawName: "Lunch Box & Thermos - 1st 1,500 Fans",
    matchup: "Memphis Hustle",
    startDate: "2026-01-30",
    endDate: "2026-01-30",
    description: " on January 30, 2026 at 7:30 p.m.",
    timeAndZone: "7:30PM EST",
    location: "Public Auditorium",
    offerURL:
      "https://cleveland.gleague.nba.com/news/cleveland-charge-unveil-2025-26-promotional-schedule",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "charge",
    eventName: "Poster Giveaway - 1st 1,500 Fans",
    rawName: "Poster Giveaway - 1st 1,500 Fans",
    matchup: "Motor City Cruise",
    startDate: "2026-01-31",
    endDate: "2026-01-31",
    description: " on January 31, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Public Auditorium",
    offerURL:
      "https://cleveland.gleague.nba.com/news/cleveland-charge-unveil-2025-26-promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "charge",
    eventName: "Beanies - 1st 1,500 Fans",
    rawName: "Beanies - 1st 1,500 Fans",
    matchup: "Greensboro Swarm",
    startDate: "2026-02-06",
    endDate: "2026-02-06",
    description: " on February 6, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Public Auditorium",
    offerURL:
      "https://cleveland.gleague.nba.com/news/cleveland-charge-unveil-2025-26-promotional-schedule",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "charge",
    eventName: "Polar Plunge Blanket - 1st 1,500 Fans",
    rawName: "Polar Plunge Blanket - 1st 1,500 Fans",
    matchup: "Greensboro Swarm",
    startDate: "2026-02-07",
    endDate: "2026-02-07",
    description: " on February 7, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Public Auditorium",
    offerURL:
      "https://cleveland.gleague.nba.com/news/cleveland-charge-unveil-2025-26-promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "charge",
    eventName: "Drawstrings Bags - 1st 5,000 Fans",
    rawName: "Drawstrings Bags - 1st 5,000 Fans",
    matchup: "Windy City Bulls",
    startDate: "2026-03-03",
    endDate: "2026-03-03",
    description: " on March 3, 2026 at 11:00 a.m.",
    timeAndZone: "11:00AM EST",
    location: "Public Auditorium",
    offerURL:
      "https://cleveland.gleague.nba.com/news/cleveland-charge-unveil-2025-26-promotional-schedule",
    dayOfWeek: "tuesday",
  },

  {
    league: "gleaguenba",
    teamName: "charge",
    eventName: "Salute to Service Shirt - 1st 1,500 Fans",
    rawName: "Salute to Service Shirt - 1st 1,500 Fans",
    matchup: "Capital City Go-Go",
    startDate: "2026-03-08",
    endDate: "2026-03-08",
    description: " on March 8, 2026 at 4:00 p.m.",
    timeAndZone: "4:00PM EST",
    location: "Public Auditorium",
    offerURL:
      "https://cleveland.gleague.nba.com/news/cleveland-charge-unveil-2025-26-promotional-schedule",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "charge",
    eventName: "Charge Scarf - 1st 1,500 Fans",
    rawName: "Charge Scarf - 1st 1,500 Fans",
    matchup: "Santa Cruz Warriors",
    startDate: "2026-03-13",
    endDate: "2026-03-13",
    description: " on March 13, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Public Auditorium",
    offerURL:
      "https://cleveland.gleague.nba.com/news/cleveland-charge-unveil-2025-26-promotional-schedule",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "charge",
    eventName: "Water Bottle - 1st 1,500 Fans",
    rawName: "Water Bottle - 1st 1,500 Fans",
    matchup: "Delaware Blue Coats",
    startDate: "2026-03-18",
    endDate: "2026-03-18",
    description: " on March 18, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Public Auditorium",
    offerURL:
      "https://cleveland.gleague.nba.com/news/cleveland-charge-unveil-2025-26-promotional-schedule",
    dayOfWeek: "wednesday",
  },

  {
    league: "gleaguenba",
    teamName: "charge",
    eventName: "NaeQwan Tomlin Bobblehead - 1st 2,000 Fans",
    rawName: "NaeQwan Tomlin Bobblehead - 1st 2,000 Fans",
    matchup: "Long Island Nets",
    startDate: "2026-03-28",
    endDate: "2026-03-28",
    description: " on March 28, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Public Auditorium",
    offerURL:
      "https://cleveland.gleague.nba.com/news/cleveland-charge-unveil-2025-26-promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "gold",
    eventName: "LED Thunderstick Giveaway",
    rawName: "LED Thunderstick Giveaway",
    matchup: "Nobelsville Boom",
    startDate: "2025-11-07",
    endDate: "2025-11-07",
    description: " on November 7, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Van Andel Arena",
    offerURL:
      "https://grandrapids.gleague.nba.com/news/grand-rapids-gold-announce-2025-26-promotional-schedule",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "gold",
    eventName: "Bucket Hat",
    rawName: "Bucket Hat",
    matchup: "Motor City Cruise",
    startDate: "2025-11-15",
    endDate: "2025-11-15",
    description: " on November 15, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Van Andel Arena",
    offerURL:
      "https://grandrapids.gleague.nba.com/news/grand-rapids-gold-announce-2025-26-promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "gold",
    eventName: "Jersey Lunch Box",
    rawName: "Jersey Lunch Box",
    matchup: "College Park Skyhawks",
    startDate: "2026-01-10",
    endDate: "2026-01-10",
    description: " on January 10, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Van Andel Arena",
    offerURL:
      "https://grandrapids.gleague.nba.com/news/grand-rapids-gold-announce-2025-26-promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "gold",
    eventName: "Mini Basketball Hoop",
    rawName: "Mini Basketball Hoop",
    matchup: "Wisconsin Herd",
    startDate: "2026-01-11",
    endDate: "2026-01-11",
    description: " on January 11, 2026 at 3:00 p.m.",
    timeAndZone: "3:00PM EST",
    location: "Van Andel Arena",
    offerURL:
      "https://grandrapids.gleague.nba.com/news/grand-rapids-gold-announce-2025-26-promotional-schedule",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "gold",
    eventName: "Buckets Pillow Stuffy",
    rawName: "Buckets Pillow Stuffy",
    matchup: "Cleveland Charge",
    startDate: "2026-01-18",
    endDate: "2026-01-18",
    description: " on January 18, 2026 at 3:00 p.m.",
    timeAndZone: "3:00PM EST",
    location: "Van Andel Arena",
    offerURL:
      "https://grandrapids.gleague.nba.com/news/grand-rapids-gold-announce-2025-26-promotional-schedule",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "gold",
    eventName: "Teenage Mutant Ninja Turtles x GR Gold Socks",
    rawName: "Teenage Mutant Ninja Turtles x GR Gold Socks",
    matchup: "Oklahoma City Blue",
    startDate: "2026-03-15",
    endDate: "2026-03-15",
    description: " on March 15, 2026 at 3:00 p.m.",
    timeAndZone: "3:00PM EST",
    location: "Van Andel Arena",
    offerURL:
      "https://grandrapids.gleague.nba.com/news/grand-rapids-gold-announce-2025-26-promotional-schedule",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "swarm",
    eventName: "10th Anniversary Swarm Rally Scarf - 1st 500 Fans ",
    rawName: "10th Anniversary Swarm Rally Scarf - 1st 500 Fans ",
    matchup: "Maine Celtics",
    startDate: "2025-11-07",
    endDate: "2025-11-07",
    description: " on November 7, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Novant Health Fieldhouse",
    offerURL:
      "https://greensboro.gleague.nba.com/news/greensboro-swarm-announces-2025-26-theme-and-promotional-schedule-for-10th-anniversary-season",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "swarm",
    eventName: "Trading Card Pack - 1st 500 Fans ",
    rawName: "Trading Card Pack - 1st 500 Fans ",
    matchup: "Maine Celtics",
    startDate: "2025-11-08",
    endDate: "2025-11-08",
    description: " on November 8, 2025 at 6:00 p.m.",
    timeAndZone: "6:00PM EST",
    location: "Novant Health Fieldhouse",
    offerURL:
      "https://greensboro.gleague.nba.com/news/greensboro-swarm-announces-2025-26-theme-and-promotional-schedule-for-10th-anniversary-season",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "swarm",
    eventName: "Education Day T-shirt - All Students ",
    rawName: "Education Day T-shirt - All Students ",
    matchup: "Raptors 905",
    startDate: "2025-11-19",
    endDate: "2025-11-19",
    description: " on November 19, 2025 at 11:00 a.m.",
    timeAndZone: "11:00AM EST",
    location: "Novant Health Fieldhouse",
    offerURL:
      "https://greensboro.gleague.nba.com/news/greensboro-swarm-announces-2025-26-theme-and-promotional-schedule-for-10th-anniversary-season",
    dayOfWeek: "wednesday",
  },

  {
    league: "gleaguenba",
    teamName: "swarm",
    eventName: "Free Kids Ticket with Purchase of Adult TIcket ",
    rawName: "Free Kids Ticket with Purchase of Adult TIcket ",
    matchup: "Capital City Go-Go",
    startDate: "2025-11-28",
    endDate: "2025-11-28",
    description: " on November 28, 2025 at 6:00 p.m.",
    timeAndZone: "6:00PM EST",
    location: "Novant Health Fieldhouse",
    offerURL:
      "https://greensboro.gleague.nba.com/news/greensboro-swarm-announces-2025-26-theme-and-promotional-schedule-for-10th-anniversary-season",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "swarm",
    eventName: "December BOGOs ",
    rawName: "December BOGOs ",
    matchup: "Iowa Wolves",
    startDate: "2025-12-27",
    endDate: "2025-12-27",
    description: " on December 27, 2025 at 6:00 p.m.",
    timeAndZone: "6:00PM EST",
    location: "Novant Health Fieldhouse",
    offerURL:
      "https://greensboro.gleague.nba.com/news/greensboro-swarm-announces-2025-26-theme-and-promotional-schedule-for-10th-anniversary-season",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "swarm",
    eventName: "December BOGOs ",
    rawName: "December BOGOs ",
    matchup: "Texas Legends",
    startDate: "2025-12-29",
    endDate: "2025-12-29",
    description: " on December 29, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Novant Health Fieldhouse",
    offerURL:
      "https://greensboro.gleague.nba.com/news/greensboro-swarm-announces-2025-26-theme-and-promotional-schedule-for-10th-anniversary-season",
    dayOfWeek: "monday",
  },

  {
    league: "gleaguenba",
    teamName: "swarm",
    eventName: "December BOGOs ",
    rawName: "December BOGOs ",
    matchup: "Texas Legends",
    startDate: "2025-12-31",
    endDate: "2025-12-31",
    description: " on December 31, 2025 at 1:00 p.m.",
    timeAndZone: "1:00PM EST",
    location: "Novant Health Fieldhouse",
    offerURL:
      "https://greensboro.gleague.nba.com/news/greensboro-swarm-announces-2025-26-theme-and-promotional-schedule-for-10th-anniversary-season",
    dayOfWeek: "wednesday",
  },

  {
    league: "gleaguenba",
    teamName: "swarm",
    eventName: "Beanie - 1st 500 Fans",
    rawName: "Beanie - 1st 500 Fans",
    matchup: "Texas Legends",
    startDate: "2025-12-29",
    endDate: "2025-12-29",
    description: " on December 29, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Novant Health Fieldhouse",
    offerURL:
      "https://greensboro.gleague.nba.com/news/greensboro-swarm-announces-2025-26-theme-and-promotional-schedule-for-10th-anniversary-season",
    dayOfWeek: "monday",
  },

  {
    league: "gleaguenba",
    teamName: "swarm",
    eventName: "Jaylen Sims Bobblehead - 1st 500 Fans",
    rawName: "Jaylen Sims Bobblehead - 1st 500 Fans",
    matchup: "Osceola Magic",
    startDate: "2026-01-17",
    endDate: "2026-01-17",
    description: " on January 17, 2026 at 6:00 p.m.",
    timeAndZone: "6:00PM EST",
    location: "Novant Health Fieldhouse",
    offerURL:
      "https://greensboro.gleague.nba.com/news/greensboro-swarm-announces-2025-26-theme-and-promotional-schedule-for-10th-anniversary-season",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "swarm",
    eventName: "Special Giveaway - Limited Supply",
    rawName: "Special Giveaway - Limited Supply",
    matchup: "Motor City Cruise",
    startDate: "2026-03-07",
    endDate: "2026-03-07",
    description: " on March 7, 2026 at 6:00 p.m.",
    timeAndZone: "6:00PM EST",
    location: "Novant Health Fieldhouse",
    offerURL:
      "https://greensboro.gleague.nba.com/news/greensboro-swarm-announces-2025-26-theme-and-promotional-schedule-for-10th-anniversary-season",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "swarm",
    eventName: "Swarmy Jeansboro Bobblehead - 1st 500 Fans",
    rawName: "Swarmy Jeansboro Bobblehead - 1st 500 Fans",
    matchup: "Osceola Magic",
    startDate: "2026-03-13",
    endDate: "2026-03-13",
    description: " on March 13, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Novant Health Fieldhouse",
    offerURL:
      "https://greensboro.gleague.nba.com/news/greensboro-swarm-announces-2025-26-theme-and-promotional-schedule-for-10th-anniversary-season",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "swarm",
    eventName: "Special Giveaway - Limited Supply",
    rawName: "Special Giveaway - Limited Supply",
    matchup: "College Park Skyhawks",
    startDate: "2026-03-27",
    endDate: "2026-03-27",
    description: " on March 27, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Novant Health Fieldhouse",
    offerURL:
      "https://greensboro.gleague.nba.com/news/greensboro-swarm-announces-2025-26-theme-and-promotional-schedule-for-10th-anniversary-season",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "swarm",
    eventName: "Special Giveaway - Limited Supply",
    rawName: "Special Giveaway - Limited Supply",
    matchup: "College Park Skyhawks",
    startDate: "2026-03-28",
    endDate: "2026-03-28",
    description: " on March 28, 2026 at 6:00 p.m.",
    timeAndZone: "6:00PM EST",
    location: "Novant Health Fieldhouse",
    offerURL:
      "https://greensboro.gleague.nba.com/news/greensboro-swarm-announces-2025-26-theme-and-promotional-schedule-for-10th-anniversary-season",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "magic",
    eventName: "Home Schedule T-Shirt",
    rawName: "Home Schedule T-Shirt",
    matchup: "Texas Legends",
    startDate: "2025-11-07",
    endDate: "2025-11-07",
    description: " on November 7, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Silver Spurs Arena",
    offerURL:
      "https://www.oursportscentral.com/services/releases/osceola-magic-announce-2025-26-season-promotional-schedule/n-6293482",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "magic",
    eventName: "Heritage Hat",
    rawName: "Heritage Hat",
    matchup: "Texas Legends",
    startDate: "2025-11-08",
    endDate: "2025-11-08",
    description: " on November 8, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Silver Spurs Arena",
    offerURL:
      "https://www.oursportscentral.com/services/releases/osceola-magic-announce-2025-26-season-promotional-schedule/n-6293482",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "magic",
    eventName: "Pint Glass",
    rawName: "Pint Glass",
    matchup: "Birmingham Squadron",
    startDate: "2025-11-08",
    endDate: "2025-11-08",
    description: " on November 8, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Silver Spurs Arena",
    offerURL:
      "https://www.oursportscentral.com/services/releases/osceola-magic-announce-2025-26-season-promotional-schedule/n-6293482",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "magic",
    eventName: "Reversable Jersey",
    rawName: "Reversable Jersey",
    matchup: "Birmingham Squadron",
    startDate: "2025-11-16",
    endDate: "2025-11-16",
    description: " on November 16, 2025 at 3:00 p.m.",
    timeAndZone: "3:00PM EST",
    location: "Silver Spurs Arena",
    offerURL:
      "https://www.oursportscentral.com/services/releases/osceola-magic-announce-2025-26-season-promotional-schedule/n-6293482",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "magic",
    eventName: "Replica Jersey",
    rawName: "Replica Jersey",
    matchup: "Memphis Hustle",
    startDate: "2025-12-14",
    endDate: "2025-12-14",
    description: " on December 14, 2025 at 3:00 p.m.",
    timeAndZone: "3:00PM EST",
    location: "Silver Spurs Arena",
    offerURL:
      "https://www.oursportscentral.com/services/releases/osceola-magic-announce-2025-26-season-promotional-schedule/n-6293482",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "magic",
    eventName: "Sweater Themed Replica Jersey",
    rawName: "Sweater Themed Replica Jersey",
    matchup: "Memphis Hustle",
    startDate: "2025-12-16",
    endDate: "2025-12-16",
    description: " on December 16, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Silver Spurs Arena",
    offerURL:
      "https://www.oursportscentral.com/services/releases/osceola-magic-announce-2025-26-season-promotional-schedule/n-6293482",
    dayOfWeek: "tuesday",
  },

  {
    league: "gleaguenba",
    teamName: "magic",
    eventName: "Porky Pig Bobblehead",
    rawName: "Porky Pig Bobblehead",
    matchup: "Raptors 905",
    startDate: "2026-01-26",
    endDate: "2026-01-26",
    description: " on January 26, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Silver Spurs Arena",
    offerURL:
      "https://www.oursportscentral.com/services/releases/osceola-magic-announce-2025-26-season-promotional-schedule/n-6293482",
    dayOfWeek: "monday",
  },

  {
    league: "gleaguenba",
    teamName: "magic",
    eventName: "Dominican Heritage Hat",
    rawName: "Dominican Heritage Hat",
    matchup: "Westchester Knicks",
    startDate: "2026-01-29",
    endDate: "2026-01-29",
    description: " on January 29, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Silver Spurs Arena",
    offerURL:
      "https://www.oursportscentral.com/services/releases/osceola-magic-announce-2025-26-season-promotional-schedule/n-6293482",
    dayOfWeek: "thursday",
  },

  {
    league: "gleaguenba",
    teamName: "magic",
    eventName: "Black History Month Hat",
    rawName: "Black History Month Hat",
    matchup: "South Bay Lakers",
    startDate: "2026-02-02",
    endDate: "2026-02-02",
    description: " on February 2, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Silver Spurs Arena",
    offerURL:
      "https://www.oursportscentral.com/services/releases/osceola-magic-announce-2025-26-season-promotional-schedule/n-6293482",
    dayOfWeek: "monday",
  },

  {
    league: "gleaguenba",
    teamName: "vipers",
    eventName: "Foam Finger - 1st 1,000 Fans",
    rawName: "Foam Finger - 1st 1,000 Fans",
    matchup: "Oklahoma City Blue",
    startDate: "2025-11-07",
    endDate: "2025-11-07",
    description: " on November 7, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "Bert Ogden Arena",
    offerURL: "https://riograndevalley.gleague.nba.com/promotional-schedule",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "vipers",
    eventName: "Viper Schedule Tee - 1st 1,000 Fans",
    rawName: "Viper Schedule Tee - 1st 1,000 Fans",
    matchup: "Texas Legends",
    startDate: "2025-11-13",
    endDate: "2025-11-13",
    description: " on November 13, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "Bert Ogden Arena",
    offerURL: "https://riograndevalley.gleague.nba.com/promotional-schedule",
    dayOfWeek: "thursday",
  },

  {
    league: "gleaguenba",
    teamName: "vipers",
    eventName: "Cowboy Cash Squishmellow - 1st 500 Fans",
    rawName: "Cowboy Cash Squishmellow - 1st 500 Fans",
    matchup: "Texas Legends",
    startDate: "2025-11-15",
    endDate: "2025-11-15",
    description: " on November 15, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "Bert Ogden Arena",
    offerURL: "https://riograndevalley.gleague.nba.com/promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "vipers",
    eventName: "Youth Viper Basketball - 1st 1,000 Fans",
    rawName: "Youth Viper Basketball - 1st 1,000 Fans",
    matchup: "Osceola Magic",
    startDate: "2025-11-29",
    endDate: "2025-11-29",
    description: " on November 29, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "Bert Ogden Arena",
    offerURL: "https://riograndevalley.gleague.nba.com/promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "vipers",
    eventName: "Vamos Vipers Rally Towell - 1st 1,000 Fans",
    rawName: "Vamos Vipers Rally Towell - 1st 1,000 Fans",
    matchup: "Mexico City Capitanes",
    startDate: "2025-12-06",
    endDate: "2025-12-06",
    description: " on December 6, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "Bert Ogden Arena",
    offerURL: "https://riograndevalley.gleague.nba.com/promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "vipers",
    eventName: "Vipers Beanie - 1st 1,000 Fans",
    rawName: "Vipers Beanie - 1st 1,000 Fans",
    matchup: "Valley Suns",
    startDate: "2026-01-03",
    endDate: "2026-01-03",
    description: " on January 3, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "Bert Ogden Arena",
    offerURL: "https://riograndevalley.gleague.nba.com/promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "vipers",
    eventName: "VipersCap - 1st 1,000 Fans",
    rawName: "VipersCap - 1st 1,000 Fans",
    matchup: "Greensboro Swarm",
    startDate: "2026-01-09",
    endDate: "2026-01-09",
    description: " on January 9, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "Bert Ogden Arena",
    offerURL: "https://riograndevalley.gleague.nba.com/promotional-schedule",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "vipers",
    eventName: "Vipers XLSNB Jersey - 1st 1,000 Fans",
    rawName: "Vipers XLSNB Jersey - 1st 1,000 Fans",
    matchup: "Greensboro Swarm",
    startDate: "2026-01-10",
    endDate: "2026-01-10",
    description: " on January 10, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "Bert Ogden Arena",
    offerURL: "https://riograndevalley.gleague.nba.com/promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "vipers",
    eventName: "Whataburger X Vipers Graphic Tee - 1st 1,000 Fans",
    rawName: "Whataburger X Vipers Graphic Tee - 1st 1,000 Fans",
    matchup: "South Bay Lakers",
    startDate: "2026-01-17",
    endDate: "2026-01-17",
    description: " on January 17, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "Bert Ogden Arena",
    offerURL: "https://riograndevalley.gleague.nba.com/promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "vipers",
    eventName: "Vipers Enamel Pin - 1st 500 Fans",
    rawName: "Vipers Enamel Pin - 1st 500 Fans",
    matchup: "South Bay Lakers",
    startDate: "2026-01-20",
    endDate: "2026-01-20",
    description: " on January 20, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "Bert Ogden Arena",
    offerURL: "https://riograndevalley.gleague.nba.com/promotional-schedule",
    dayOfWeek: "tuesday",
  },

  {
    league: "gleaguenba",
    teamName: "vipers",
    eventName: "Vipers Blanket - 1st 1,000 Fans",
    rawName: "Vipers Blanket - 1st 1,000 Fans",
    matchup: "Rio City Remix",
    startDate: "2026-01-22",
    endDate: "2026-01-22",
    description: " on January 22, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "Bert Ogden Arena",
    offerURL: "https://riograndevalley.gleague.nba.com/promotional-schedule",
    dayOfWeek: "thursday",
  },

  {
    league: "gleaguenba",
    teamName: "vipers",
    eventName: "Vipers Football Jersey - 1st 1,000 Fans",
    rawName: "Vipers Football Jersey - 1st 1,000 Fans",
    matchup: "Austin Spurs",
    startDate: "2026-02-07",
    endDate: "2026-02-07",
    description: " on February 7, 2026 at 8:00 p.m.",
    timeAndZone: "8:00PM CST",
    location: "Bert Ogden Arena",
    offerURL: "https://riograndevalley.gleague.nba.com/promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "vipers",
    eventName: "Vipers Umbrella - 1st 1,000 Fans",
    rawName: "Vipers Umbrella - 1st 1,000 Fans",
    matchup: "Noblesville Boom",
    startDate: "2026-02-27",
    endDate: "2026-02-27",
    description: " on February 27, 2026 at 6:30 p.m.",
    timeAndZone: "6:30PM CST",
    location: "Bert Ogden Arena",
    offerURL: "https://riograndevalley.gleague.nba.com/promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "vipers",
    eventName: "Vipers Windbreaker - 1st 1,000 Fans",
    rawName: "Vipers Windbreaker - 1st 1,000 Fans",
    matchup: "Salt Lake City Stars",
    startDate: "2026-03-13",
    endDate: "2026-03-13",
    description: " on March 13, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "Bert Ogden Arena",
    offerURL: "https://riograndevalley.gleague.nba.com/promotional-schedule",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "vipers",
    eventName: "Viper XLSNB Jersey - 1st 1,000 Fans",
    rawName: "Viper XLSNB Jersey - 1st 1,000 Fans",
    matchup: "Salt Lake City Stars",
    startDate: "2026-03-14",
    endDate: "2026-03-14",
    description: " on March 14, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "Bert Ogden Arena",
    offerURL: "https://riograndevalley.gleague.nba.com/promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "vipers",
    eventName: "Vipers Light Saber - 1st 1,000 Fans",
    rawName: "Vipers Light Saber - 1st 1,000 Fans",
    matchup: "Memphis Hustle",
    startDate: "2026-03-26",
    endDate: "2026-03-26",
    description: " on March 26, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "Bert Ogden Arena",
    offerURL: "https://riograndevalley.gleague.nba.com/promotional-schedule",
    dayOfWeek: "thursday",
  },

  {
    league: "gleaguenba",
    teamName: "stars",
    eventName: "Home Jersey - 1st 1,000 Fans",
    rawName: "Home Jersey - 1st 1,000 Fans",
    matchup: "South Bay Lakers",
    startDate: "2025-11-18",
    endDate: "2025-11-18",
    description: " on November 18, 2025 at 6:00 p.m.",
    timeAndZone: "6:00PM PST",
    location: "Maverick Center",
    offerURL:
      "https://saltlakecity.gleague.nba.com/news/slc-stars-announce-2025-26-promotional-schedule-single-game-tickets-now-on-sale",
    dayOfWeek: "tuesday",
  },

  {
    league: "gleaguenba",
    teamName: "stars",
    eventName: "West Valley Jersey - 1st 500 Fans",
    rawName: "West Valley Jersey - 1st 500 Fans",
    matchup: "Valley Suns",
    startDate: "2025-12-15",
    endDate: "2025-12-15",
    description: " on December 15, 2025 at 5:30 p.m.",
    timeAndZone: "5:30PM PST",
    location: "Maverick Center",
    offerURL:
      "https://saltlakecity.gleague.nba.com/news/slc-stars-announce-2025-26-promotional-schedule-single-game-tickets-now-on-sale",
    dayOfWeek: "monday",
  },

  {
    league: "gleaguenba",
    teamName: "stars",
    eventName: "West Valley Jersey - 1st 500 Fans",
    rawName: "West Valley Jersey - 1st 500 Fans",
    matchup: "Austin Spurs",
    startDate: "2026-01-13",
    endDate: "2026-01-13",
    description: " on January 13, 2026 at 5:00 p.m.",
    timeAndZone: "5:00PM PST",
    location: "Maverick Center",
    offerURL:
      "https://saltlakecity.gleague.nba.com/news/slc-stars-announce-2025-26-promotional-schedule-single-game-tickets-now-on-sale",
    dayOfWeek: "tuesday",
  },

  {
    league: "gleaguenba",
    teamName: "stars",
    eventName: "West Valley Jersey - 1st 500 Fans",
    rawName: "West Valley Jersey - 1st 500 Fans",
    matchup: "Westchester Knicks",
    startDate: "2026-02-06",
    endDate: "2026-02-06",
    description: " on February 6, 2025 at 5:00 p.m.",
    timeAndZone: "5:00PM PST",
    location: "Maverick Center",
    offerURL:
      "https://saltlakecity.gleague.nba.com/news/slc-stars-announce-2025-26-promotional-schedule-single-game-tickets-now-on-sale",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "stars",
    eventName: "ABA Throwback Jersey - 1st 500 Fans",
    rawName: "ABA Throwback Jersey - 1st 500 Fans",
    matchup: "Austin Spurs",
    startDate: "2026-01-15",
    endDate: "2026-01-15",
    description: " on January 15, 2026 at 5:00 p.m.",
    timeAndZone: "5:00PM PST",
    location: "Maverick Center",
    offerURL:
      "https://saltlakecity.gleague.nba.com/news/slc-stars-announce-2025-26-promotional-schedule-single-game-tickets-now-on-sale",
    dayOfWeek: "thursday",
  },

  {
    league: "gleaguenba",
    teamName: "stars",
    eventName: "Las Estrellas Jersey - 1st 500 Fans",
    rawName: "Las Estrellas Jersey - 1st 500 Fans",
    matchup: "Oklahoma City Blue",
    startDate: "2026-02-20",
    endDate: "2026-02-20",
    description: " on February 20, 2026 at 5:00 p.m.",
    timeAndZone: "5:00PM PST",
    location: "Maverick Center",
    offerURL:
      "https://saltlakecity.gleague.nba.com/news/slc-stars-announce-2025-26-promotional-schedule-single-game-tickets-now-on-sale",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "wolves",
    eventName: "T-Shirt - 1st 1,500 Fans",
    rawName: "T-Shirt - 1st 1,500 Fans",
    matchup: "Cleveland Charge",
    startDate: "2025-11-07",
    endDate: "2025-11-07",
    description: " on November 7, 2025 at 6:30 p.m.",
    timeAndZone: "6:30PM CST",
    location: "Casey's Center",
    offerURL: "https://iowa.gleague.nba.com/promos",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "wolves",
    eventName: "TBA Giveaway",
    rawName: "TBA Giveaway",
    matchup: "Cleveland Charge",
    startDate: "2025-11-08",
    endDate: "2025-11-08",
    description: " on November 8, 2025 at 6:30 p.m.",
    timeAndZone: "6:30PM CST",
    location: "Casey's Center",
    offerURL: "https://iowa.gleague.nba.com/promos",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "wolves",
    eventName: "TBA Giveaway",
    rawName: "TBA Giveaway",
    matchup: "Windy City Bulls",
    startDate: "2025-11-21",
    endDate: "2025-11-21",
    description: " on November 21, 2025 at 6:30 p.m.",
    timeAndZone: "6:30PM CST",
    location: "Casey's Center",
    offerURL: "https://iowa.gleague.nba.com/promos",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "wolves",
    eventName: "Beanie - 1st 1,500 fans",
    rawName: "Beanie - 1st 1,500 fans",
    matchup: "Motor City Cruise",
    startDate: "2025-12-12",
    endDate: "2025-12-12",
    description: " on December 12, 2025 at 6:30 p.m.",
    timeAndZone: "6:30PM CST",
    location: "Casey's Center",
    offerURL: "https://iowa.gleague.nba.com/promos",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "wolves",
    eventName: "youth Jersey - 1st 1,500 fans",
    rawName: "youth Jersey - 1st 1,500 fans",
    matchup: "Sioux Falls Skyforce",
    startDate: "2026-01-03",
    endDate: "2026-01-03",
    description: " on January 3, 2026 at 6:30 p.m.",
    timeAndZone: "6:30PM CST",
    location: "Casey's Center",
    offerURL: "https://iowa.gleague.nba.com/promos",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "wolves",
    eventName: "Pit Viper- 1st 1,500 fans",
    rawName: "Pit Viper- 1st 1,500 fans",
    matchup: "Long Island Nets",
    startDate: "2026-01-18",
    endDate: "2026-01-18",
    description: " on January 18, 2026 at 1:00 p.m.",
    timeAndZone: "1:00PM CST",
    location: "Casey's Center",
    offerURL: "https://iowa.gleague.nba.com/promos",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "wolves",
    eventName: "Butter Bell - 1st 1,500 fans",
    rawName: "Butter Bell - 1st 1,500 fans",
    matchup: "Rio Grande Valley Vipers",
    startDate: "2026-02-22",
    endDate: "2026-02-22",
    description: " on February 22, 2026 at 3:00 p.m.",
    timeAndZone: "3:00PM CST",
    location: "Casey's Center",
    offerURL: "https://iowa.gleague.nba.com/promos",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "wolves",
    eventName: "TBA Giveaway",
    rawName: "TBA Giveaway",
    matchup: "Mexico City Capitanes",
    startDate: "2026-02-27",
    endDate: "2026-02-27",
    description: " on February 27, 2026 at 6:30 p.m.",
    timeAndZone: "6:30PM CST",
    location: "Casey's Center",
    offerURL: "https://iowa.gleague.nba.com/promos",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "wolves",
    eventName: "Tumbler Giveaway",
    rawName: "Tumbler Giveaway",
    matchup: "Memphis Hustle",
    startDate: "2026-03-08",
    endDate: "2026-03-08",
    description: " on March 8, 2026 at 1:00 p.m.",
    timeAndZone: "1:00PM CST",
    location: "Casey's Center",
    offerURL: "https://iowa.gleague.nba.com/promos",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "wolves",
    eventName: "Fanny Pack Hat Giveaway - 1st 1,500 Fans",
    rawName: "Fanny Pack Hat Giveaway - 1st 1,500 Fans",
    matchup: "Memphis Hustle",
    startDate: "2026-03-28",
    endDate: "2026-03-28",
    description: " on March 28, 2026 at 6:30 p.m.",
    timeAndZone: "6:30PM CST",
    location: "Casey's Center",
    offerURL: "https://iowa.gleague.nba.com/promos",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "celtics",
    eventName: "Rally Towel Giveaway",
    rawName: "Rally Towel Giveaway",
    matchup: "Long Island Nets",
    startDate: "2025-11-14",
    endDate: "2025-11-14",
    description: " on November 14, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM EST",
    location: "Portland Expo",
    offerURL: "https://maine.gleague.nba.com/promtional-schedule-2025-26",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "celtics",
    eventName: "T-Shirt Giveaway",
    rawName: "T-Shirt Giveaway",
    matchup: "Raptors 905",
    startDate: "2025-12-14",
    endDate: "2025-12-14",
    description: " on December 14, 2025 at 1:00 p.m.",
    timeAndZone: "1:00PM EST",
    location: "Portland Expo",
    offerURL: "https://maine.gleague.nba.com/promtional-schedule-2025-26",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "celtics",
    eventName: "Team Poster Giveaway & Team Post Game Autographs",
    rawName: "Team Poster Giveaway & Team Post Game Autographs",
    matchup: "Cleveland Charge",
    startDate: "2026-03-22",
    endDate: "2026-03-22",
    description: " on March 22, 2025 at 12:00 p.m.",
    timeAndZone: "12:00PM EST",
    location: "Portland Expo",
    offerURL: "https://maine.gleague.nba.com/promtional-schedule-2025-26",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "clippers",
    eventName: "Schedule Magnet",
    rawName: "Schedule Magnet",
    matchup: "Salt Lake City Stars",
    startDate: "2025-11-16",
    endDate: "2025-11-16",
    description: " on November 16, 2025 at 6:00 p.m.",
    timeAndZone: "6:00PM PST",
    location: "Frontwave Arena",
    offerURL: "https://fox5sandiego.com/sports/san-diego-clippers-promotions",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "clippers",
    eventName: "Corduroy Hat Giveaway; Special Cooler Bag Ticket Package",
    rawName: "Corduroy Hat Giveaway; Special Cooler Bag Ticket Package",
    matchup: "Rip City Remix",
    startDate: "2025-11-23",
    endDate: "2025-11-23",
    description: " on November 23, 2025 at 6:00 p.m.",
    timeAndZone: "6:00PM PST",
    location: "Frontwave Arena",
    offerURL: "https://fox5sandiego.com/sports/san-diego-clippers-promotions",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "clippers",
    eventName: "Community Weekend - Headbands and Thundersticks",
    rawName: "Community Weekend - Headbands and Thundersticks",
    matchup: "South Bay Lakers",
    startDate: "2025-11-29",
    endDate: "2025-11-29",
    description: " on November 29, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM PST",
    location: "Frontwave Arena",
    offerURL: "https://fox5sandiego.com/sports/san-diego-clippers-promotions",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "clippers",
    eventName: "Community Weekend - Headbands and Thundersticks",
    rawName: "Community Weekend - Headbands and Thundersticks",
    matchup: "South Bay Lakers",
    startDate: "2025-11-30",
    endDate: "2025-11-30",
    description: " on November 30, 2025 at 6:00 p.m.",
    timeAndZone: "6:00PM PST",
    location: "Frontwave Arena",
    offerURL: "https://fox5sandiego.com/sports/san-diego-clippers-promotions",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "clippers",
    eventName: "Holiday Socks and Blanket Ticket Packages",
    rawName: "Holiday Socks and Blanket Ticket Packages",
    matchup: "Santa Cruz Warriors",
    startDate: "2025-12-13",
    endDate: "2025-12-13",
    description: " on December 13, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM PST",
    location: "Frontwave Arena",
    offerURL: "https://fox5sandiego.com/sports/san-diego-clippers-promotions",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "clippers",
    eventName: "Hawaiian Shirt",
    rawName: "Hawaiian Shirt",
    matchup: "Santa Cruz Warriors",
    startDate: "2025-12-14",
    endDate: "2025-12-14",
    description: " on December 14, 2025 at 6:00 p.m.",
    timeAndZone: "6:00PM PST",
    location: "Frontwave Arena",
    offerURL: "https://fox5sandiego.com/sports/san-diego-clippers-promotions",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "clippers",
    eventName: "Mascot Shoulder Pets",
    rawName: "Mascot Shoulder Pets",
    matchup: "Sioux Falls Skyforce",
    startDate: "2025-12-27",
    endDate: "2025-12-27",
    description: " on December 27, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM PST",
    location: "Frontwave Arena",
    offerURL: "https://fox5sandiego.com/sports/san-diego-clippers-promotions",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "clippers",
    eventName: "Cowboy Hat",
    rawName: "Cowboy Hat",
    matchup: "Sioux Falls Skyforce",
    startDate: "2025-12-28",
    endDate: "2025-12-28",
    description: " on December 28, 2025 at 6:00 p.m.",
    timeAndZone: "6:00PM PST",
    location: "Frontwave Arena",
    offerURL: "https://fox5sandiego.com/sports/san-diego-clippers-promotions",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "clippers",
    eventName: "Lightsaber Thundersticks; Replica Jersey Ticket Package",
    rawName: "Lightsaber Thundersticks; Replica Jersey Ticket Package",
    matchup: "Oklahoma City Blue",
    startDate: "2026-01-24",
    endDate: "2026-01-24",
    description: " on January 24, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM PST",
    location: "Frontwave Arena",
    offerURL: "https://fox5sandiego.com/sports/san-diego-clippers-promotions",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "clippers",
    eventName: "Bill Walton Bobblehead",
    rawName: "Bill Walton Bobblehead",
    matchup: "College Park Skyhawks",
    startDate: "2026-01-31",
    endDate: "2026-01-31",
    description: " on January 31, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM PST",
    location: "Frontwave Arena",
    offerURL: "https://fox5sandiego.com/sports/san-diego-clippers-promotions",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "clippers",
    eventName: "Bill Walton Bobblehead",
    rawName: "Bill Walton Bobblehead",
    matchup: "College Park Skyhawks",
    startDate: "2026-01-31",
    endDate: "2026-01-31",
    description: " on January 31, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM PST",
    location: "Frontwave Arena",
    offerURL: "https://fox5sandiego.com/sports/san-diego-clippers-promotions",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "clippers",
    eventName: "Tote Bag Giveaway; Themed T-Shirt Ticket Package",
    rawName: "Tote Bag Giveaway; Themed T-Shirt Ticket Package",
    matchup: "Austin Spurs",
    startDate: "2026-02-20",
    endDate: "2026-02-20",
    description: " on February 20, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM PST",
    location: "Frontwave Arena",
    offerURL: "https://fox5sandiego.com/sports/san-diego-clippers-promotions",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "clippers",
    eventName: "Lucha Libre Mask Giveaway; Ponch Ticket Package",
    rawName: "Lucha Libre Mask Giveaway; Ponch Ticket Package",
    matchup: "Valley Suns",
    startDate: "2026-03-21",
    endDate: "2026-03-21",
    description: " on March 21, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM PST",
    location: "Frontwave Arena",
    offerURL: "https://fox5sandiego.com/sports/san-diego-clippers-promotions",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "clippers",
    eventName: "Replica Jersey Giveaway",
    rawName: "Replica Jersey Giveaway",
    matchup: "Stockton Kings",
    startDate: "2026-03-28",
    endDate: "2026-03-28",
    description: " on March 28, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM PST",
    location: "Frontwave Arena",
    offerURL: "https://fox5sandiego.com/sports/san-diego-clippers-promotions",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "clippers",
    eventName: "Wellness Night - Eye Mask Giveaway",
    rawName: "Wellness Night - Eye Mask Giveaway",
    matchup: "Austin Spurs",
    startDate: "2026-02-19",
    endDate: "2026-02-19",
    description: " on February 19, 2026 at 7:30 p.m.",
    timeAndZone: "7:30PM PST",
    location: "Frontwave Arena",
    offerURL: "https://fox5sandiego.com/sports/san-diego-clippers-promotions",
    dayOfWeek: "thursday",
  },

  {
    league: "gleaguenba",
    teamName: "clippers",
    eventName: "Heroes Night - Cape Giveaway",
    rawName: "Heroes Night - Cape Giveaway",
    matchup: "Rip City Remix",
    startDate: "2026-03-12",
    endDate: "2026-03-12",
    description: " on March 12, 2026 at 7:30 p.m.",
    timeAndZone: "7:30PM PST",
    location: "Frontwave Arena",
    offerURL: "https://fox5sandiego.com/sports/san-diego-clippers-promotions",
    dayOfWeek: "thursday",
  },

  {
    league: "gleaguenba",
    teamName: "clippers",
    eventName: "Education Day - Drawstring Bag Giveaway",
    rawName: "Education Day - Drawstring Bag Giveaway",
    matchup: "Valley Suns",
    startDate: "2026-03-19",
    endDate: "2026-03-19",
    description: " on March 19, 2026 at 12:00 p.m.",
    timeAndZone: "12:00PM PST",
    location: "Frontwave Arena",
    offerURL: "https://fox5sandiego.com/sports/san-diego-clippers-promotions",
    dayOfWeek: "thursday",
  },

  {
    league: "gleaguenba",
    teamName: "clippers",
    eventName:
      "Collectors Night - Limited edition 1 of 1 Jerseys and Exclusive Trading Cards",
    rawName:
      "Collectors Night - Limited edition 1 of 1 Jerseys and Exclusive Trading Cards",
    matchup: "Iowa Wolves",
    startDate: "2026-01-10",
    endDate: "2026-01-10",
    description: " on January 10, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM PST",
    location: "Frontwave Arena",
    offerURL: "https://fox5sandiego.com/sports/san-diego-clippers-promotions",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "clippers",
    eventName: "College Night - Pint Glass Giveaway",
    rawName: "College Night - Pint Glass Giveaway",
    matchup: "College Park Skyhawks",
    startDate: "2026-01-30",
    endDate: "2026-01-30",
    description: " on January 30, 2026 at 7:30 p.m.",
    timeAndZone: "7:30PM PST",
    location: "Frontwave Arena",
    offerURL: "https://fox5sandiego.com/sports/san-diego-clippers-promotions",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "warriors",
    eventName: "2025 Opening Night T-Shirt- All Fans",
    rawName: "2025 Opening Night T-Shirt- All Fans",
    matchup: "Rip City Remix",
    startDate: "2025-11-07",
    endDate: "2025-11-07",
    description: " on November 7, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM PST",
    location: "Kaiser Permanente Arena",
    offerURL: "https://santacruz.gleague.nba.com/2025-26-promotional-schedule",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "warriors",
    eventName: "2025-26 Season Schedule Magnet - All Fans",
    rawName: "2025-26 Season Schedule Magnet - All Fans",
    matchup: "Rip City Remix",
    startDate: "2025-11-08",
    endDate: "2025-11-08",
    description: " on November 8, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM PST",
    location: "Kaiser Permanente Arena",
    offerURL: "https://santacruz.gleague.nba.com/2025-26-promotional-schedule",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "warriors",
    eventName:
      "Rally Towel & Stephen Curry All-Star MVP Bobblehead - 1st 1,000 Fans",
    rawName:
      "Rally Towel & Stephen Curry All-Star MVP Bobblehead - 1st 1,000 Fans",
    matchup: "Stockton Kings",
    startDate: "2025-11-14",
    endDate: "2025-11-14",
    description: " on November 14, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM PST",
    location: "Kaiser Permanente Arena",
    offerURL: "https://santacruz.gleague.nba.com/2025-26-promotional-schedule",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "warriors",
    eventName:
      "Jimmy Butler and Buddy Hield Best Buddies Bobblehead - 1st 1,000 Fans",
    rawName:
      "Jimmy Butler and Buddy Hield Best Buddies Bobblehead - 1st 1,000 Fans",
    matchup: "Stockton Kings",
    startDate: "2025-11-15",
    endDate: "2025-11-15",
    description: " on November 15, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM PST",
    location: "Kaiser Permanente Arena",
    offerURL: "https://santacruz.gleague.nba.com/2025-26-promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "warriors",
    eventName: "Stephen Curry Bobblehead - 1st 1,000 Fans",
    rawName: "Stephen Curry Bobblehead - 1st 1,000 Fans",
    matchup: "Salt Lake City Stars",
    startDate: "2025-11-28",
    endDate: "2025-11-28",
    description: " on November 28, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM PST",
    location: "Kaiser Permanente Arena",
    offerURL: "https://santacruz.gleague.nba.com/2025-26-promotional-schedule",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "warriors",
    eventName: "TBA Giveaway",
    rawName: "TBA Giveaway",
    matchup: "Salt Lake City Stars",
    startDate: "2025-11-28",
    endDate: "2025-11-28",
    description: " on November 29, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM PST",
    location: "Kaiser Permanente Arena",
    offerURL: "https://santacruz.gleague.nba.com/2025-26-promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "warriors",
    eventName: "Construction Mav'Riks Bobblehead - 1st 1,000 Fans",
    rawName: "Construction Mav'Riks Bobblehead - 1st 1,000 Fans",
    matchup: "Valley Suns",
    startDate: "2025-12-07",
    endDate: "2025-12-07",
    description: " on December 7, 2025 at 2:00 p.m.",
    timeAndZone: "2:00PM PST",
    location: "Kaiser Permanente Arena",
    offerURL: "https://santacruz.gleague.nba.com/2025-26-promotional-schedule",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "warriors",
    eventName: "Santa Cruz Warriors Toiletry Bag - 1st 1,000 Fans",
    rawName: "Santa Cruz Warriors Toiletry Bag - 1st 1,000 Fans",
    matchup: "Osceola Magic",
    startDate: "2025-12-27",
    endDate: "2025-12-27",
    description: " on December 27, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM PST",
    location: "Kaiser Permanente Arena",
    offerURL: "https://santacruz.gleague.nba.com/2025-26-promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "warriors",
    eventName: "SCW Hat - 1st 1,000 Fans",
    rawName: "SCW Hat - 1st 1,000 Fans",
    matchup: "Osceola Magic",
    startDate: "2025-12-28",
    endDate: "2025-12-28",
    description: " on December 28, 2025 at 6:00 p.m.",
    timeAndZone: "6:00PM PST",
    location: "Kaiser Permanente Arena",
    offerURL: "https://santacruz.gleague.nba.com/2025-26-promotional-schedule",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "warriors",
    eventName: "TBA Giveaway",
    rawName: "TBA Giveaway",
    matchup: "Sioux Falls Skyforce",
    startDate: "2026-01-23",
    endDate: "2026-01-23",
    description: " on January 23, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM PST",
    location: "Kaiser Permanente Arena",
    offerURL: "https://santacruz.gleague.nba.com/2025-26-promotional-schedule",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "warriors",
    eventName: "Clear Fanny Pack - 1st 1,000 Fans",
    rawName: "Clear Fanny Pack - 1st 1,000 Fans",
    matchup: "Sioux Falls Skyforce",
    startDate: "2026-01-24",
    endDate: "2026-01-24",
    description: " on January 24, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM PST",
    location: "Kaiser Permanente Arena",
    offerURL: "https://santacruz.gleague.nba.com/2025-26-promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "warriors",
    eventName: "TBA Giveaway",
    rawName: "TBA Giveaway",
    matchup: "Iowa Wolves",
    startDate: "2026-01-30",
    endDate: "2026-01-30",
    description: " on January 30, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM PST",
    location: "Kaiser Permanente Arena",
    offerURL: "https://santacruz.gleague.nba.com/2025-26-promotional-schedule",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "warriors",
    eventName: "TBA Giveaway",
    rawName: "TBA Giveaway",
    matchup: "Iowa Wolves",
    startDate: "2026-01-31",
    endDate: "2026-01-31",
    description: " on January 31, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM PST",
    location: "Kaiser Permanente Arena",
    offerURL: "https://santacruz.gleague.nba.com/2025-26-promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "warriors",
    eventName: "TBA Giveaway",
    rawName: "TBA Giveaway",
    matchup: "San Diego Clippers",
    startDate: "2026-03-01",
    endDate: "2026-03-01",
    description: " on March 1, 2026 at 1:00 p.m.",
    timeAndZone: "1:00PM PST",
    location: "Kaiser Permanente Arena",
    offerURL: "https://santacruz.gleague.nba.com/2025-26-promotional-schedule",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "warriors",
    eventName: "TBA Giveaway",
    rawName: "TBA Giveaway",
    matchup: "South Bay Lakers",
    startDate: "2026-03-06",
    endDate: "2026-03-06",
    description: " on March 6, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM PST",
    location: "Kaiser Permanente Arena",
    offerURL: "https://santacruz.gleague.nba.com/2025-26-promotional-schedule",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "warriors",
    eventName: "Warriors Hat - 1st 1,000 Fans",
    rawName: "Warriors Hat - 1st 1,000 Fans",
    matchup: "South Bay Lakers",
    startDate: "2026-03-08",
    endDate: "2026-03-08",
    description: " on March 8, 2026 at 5:00 p.m.",
    timeAndZone: "5:00PM PST",
    location: "Kaiser Permanente Arena",
    offerURL: "https://santacruz.gleague.nba.com/2025-26-promotional-schedule",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "warriors",
    eventName: "TBA Giveaway",
    rawName: "TBA Giveaway",
    matchup: "Rio Grande Valley Vipers",
    startDate: "2026-03-19",
    endDate: "2026-03-19",
    description: " on March 19, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM PST",
    location: "Kaiser Permanente Arena",
    offerURL: "https://santacruz.gleague.nba.com/2025-26-promotional-schedule",
    dayOfWeek: "thursday",
  },

  {
    league: "gleaguenba",
    teamName: "warriors",
    eventName: "Santa Cruz Surfers Mini Beach Cooler - 1st 1,000 Fans",
    rawName: "Santa Cruz Surfers Mini Beach Cooler - 1st 1,000 Fans",
    matchup: "Rio Grande Valley Vipers",
    startDate: "2026-03-21",
    endDate: "2026-03-21",
    description: " on March 21, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM PST",
    location: "Kaiser Permanente Arena",
    offerURL: "https://santacruz.gleague.nba.com/2025-26-promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "warriors",
    eventName: "TBA Giveaway",
    rawName: "TBA Giveaway",
    matchup: "Texas Legends",
    startDate: "2026-03-27",
    endDate: "2026-03-27",
    description: " on March 27, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM PST",
    location: "Kaiser Permanente Arena",
    offerURL: "https://santacruz.gleague.nba.com/2025-26-promotional-schedule",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "warriors",
    eventName: "Fan Appreciation Night",
    rawName: "Fan Appreciation Night",
    matchup: "Texas Legends",
    startDate: "2026-03-28",
    endDate: "2026-03-28",
    description: " on March 28, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM PST",
    location: "Kaiser Permanente Arena",
    offerURL: "https://santacruz.gleague.nba.com/2025-26-promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "herd",
    eventName: "Military Appreciation Hat - 1st 1,000 Fans",
    rawName: "Military Appreciation Hat - 1st 1,000 Fans",
    matchup: "Windy City Bulls",
    startDate: "2025-11-11",
    endDate: "2025-11-11",
    description: " on November 11, 2025 at 6:00 p.m.",
    timeAndZone: "6:00PM CST",
    location: "Oshkosh Arena",
    offerURL:
      "https://wisconsin.gleague.nba.com/2024-25-promotion-schedule?mkt_tok=MDQ1LUtSQS01OTgAAAGdRCMofuh8PrnuYD56uFkkTTuGA3SIbX4iSLOPTf_ML7zoWWCUAPekTvesmOMXwD8nSDvI-bYVzILUXU5A-gw",
    dayOfWeek: "tuesday",
  },

  {
    league: "gleaguenba",
    teamName: "herd",
    eventName: "Herd Schedule Magnet - 1st 1,000 Fans",
    rawName: "Herd Schedule Magnet - 1st 1,000 Fans",
    matchup: "Grand Rapids Gold",
    startDate: "2025-11-19",
    endDate: "2025-11-19",
    description: " on November 19, 2025 at 6:00 p.m.",
    timeAndZone: "6:00PM CST",
    location: "Oshkosh Arena",
    offerURL:
      "https://wisconsin.gleague.nba.com/2024-25-promotion-schedule?mkt_tok=MDQ1LUtSQS01OTgAAAGdRCMofuh8PrnuYD56uFkkTTuGA3SIbX4iSLOPTf_ML7zoWWCUAPekTvesmOMXwD8nSDvI-bYVzILUXU5A-gw",
    dayOfWeek: "wednesday",
  },

  {
    league: "gleaguenba",
    teamName: "herd",
    eventName: "Herd Youth Jersey - 1st 1,000 Youth Fans",
    rawName: "Herd Youth Jersey - 1st 1,000 Youth Fans",
    matchup: "Grand Rapids Gold",
    startDate: "2025-12-13",
    endDate: "2025-12-13",
    description: " on December 13, 2025 at 12:00 p.m.",
    timeAndZone: "12:00PM CST",
    location: "Oshkosh Arena",
    offerURL:
      "https://wisconsin.gleague.nba.com/2024-25-promotion-schedule?mkt_tok=MDQ1LUtSQS01OTgAAAGdRCMofuh8PrnuYD56uFkkTTuGA3SIbX4iSLOPTf_ML7zoWWCUAPekTvesmOMXwD8nSDvI-bYVzILUXU5A-gw",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "herd",
    eventName: "G.O.A.T. Bobblehead - 1st 1,000 Fans",
    rawName: "G.O.A.T. Bobblehead - 1st 1,000 Fans",
    matchup: "Iowa Wolves",
    startDate: "2025-12-16",
    endDate: "2025-12-16",
    description: " on December 16, 2025 at 6:00 p.m.",
    timeAndZone: "6:00PM CST",
    location: "Oshkosh Arena",
    offerURL:
      "https://wisconsin.gleague.nba.com/2024-25-promotion-schedule?mkt_tok=MDQ1LUtSQS01OTgAAAGdRCMofuh8PrnuYD56uFkkTTuGA3SIbX4iSLOPTf_ML7zoWWCUAPekTvesmOMXwD8nSDvI-bYVzILUXU5A-gw",
    dayOfWeek: "tuesday",
  },

  {
    league: "gleaguenba",
    teamName: "herd",
    eventName: "Herd Player Calendar - 1st 1,000 Fans",
    rawName: "Herd Player Calendar - 1st 1,000 Fans",
    matchup: "College Park Skyhawks",
    startDate: "2026-01-05",
    endDate: "2026-01-05",
    description: " on January 5, 2026 at 6:00 p.m.",
    timeAndZone: "6:00PM CST",
    location: "Oshkosh Arena",
    offerURL:
      "https://wisconsin.gleague.nba.com/2024-25-promotion-schedule?mkt_tok=MDQ1LUtSQS01OTgAAAGdRCMofuh8PrnuYD56uFkkTTuGA3SIbX4iSLOPTf_ML7zoWWCUAPekTvesmOMXwD8nSDvI-bYVzILUXU5A-gw",
    dayOfWeek: "monday",
  },

  {
    league: "gleaguenba",
    teamName: "herd",
    eventName: "Herd x Star Wars T-Shirt - 1st 1,000 Fans",
    rawName: "Herd x Star Wars T-Shirt - 1st 1,000 Fans",
    matchup: "Westchester Knicks",
    startDate: "2026-01-17",
    endDate: "2026-01-17",
    description: " on January 17, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "Oshkosh Arena",
    offerURL:
      "https://wisconsin.gleague.nba.com/2024-25-promotion-schedule?mkt_tok=MDQ1LUtSQS01OTgAAAGdRCMofuh8PrnuYD56uFkkTTuGA3SIbX4iSLOPTf_ML7zoWWCUAPekTvesmOMXwD8nSDvI-bYVzILUXU5A-gw",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "herd",
    eventName: "Herd Lunch Box - 1st 3,500 Fans",
    rawName: "Herd Lunch Box - 1st 3,500 Fans",
    matchup: "Nobelsville Boom",
    startDate: "2026-01-22",
    endDate: "2026-01-22",
    description: " on January 22, 2026 at 11:30 a.m.",
    timeAndZone: "11:30AM CST",
    location: "Oshkosh Arena",
    offerURL:
      "https://wisconsin.gleague.nba.com/2024-25-promotion-schedule?mkt_tok=MDQ1LUtSQS01OTgAAAGdRCMofuh8PrnuYD56uFkkTTuGA3SIbX4iSLOPTf_ML7zoWWCUAPekTvesmOMXwD8nSDvI-bYVzILUXU5A-gw",
    dayOfWeek: "thursday",
  },

  {
    league: "gleaguenba",
    teamName: "herd",
    eventName: "Herd Root Beer Can - 1st 1,000 Fans",
    rawName: "Herd Root Beer Can - 1st 1,000 Fans",
    matchup: "Nobelsville Boom",
    startDate: "2026-01-24",
    endDate: "2026-01-24",
    description: " on January 24, 2026 at 5:00 p.m.",
    timeAndZone: "5:00PM CST",
    location: "Oshkosh Arena",
    offerURL:
      "https://wisconsin.gleague.nba.com/2024-25-promotion-schedule?mkt_tok=MDQ1LUtSQS01OTgAAAGdRCMofuh8PrnuYD56uFkkTTuGA3SIbX4iSLOPTf_ML7zoWWCUAPekTvesmOMXwD8nSDvI-bYVzILUXU5A-gw",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "herd",
    eventName: "Wisconsin Curd Theme Night Jersey - 1st 1,000 Fans",
    rawName: "Wisconsin Curd Theme Night Jersey - 1st 1,000 Fans",
    matchup: "Birmingham Squadron",
    startDate: "2026-02-09",
    endDate: "2026-02-09",
    description: " on February 9, 2026 at 6:30 p.m.",
    timeAndZone: "6:30PM CST",
    location: "Oshkosh Arena",
    offerURL:
      "https://wisconsin.gleague.nba.com/2024-25-promotion-schedule?mkt_tok=MDQ1LUtSQS01OTgAAAGdRCMofuh8PrnuYD56uFkkTTuGA3SIbX4iSLOPTf_ML7zoWWCUAPekTvesmOMXwD8nSDvI-bYVzILUXU5A-gw",
    dayOfWeek: "monday",
  },
  {
    league: "gleaguenba",
    teamName: "herd",
    eventName:
      "La Catrina Sugar Skull Bobblehead Part 1 of Set - 1st 1,000 Fans",
    rawName: "La Catrina Sugar Skull Bobblehead Part 1 of Set - 1st 1,000 Fans",
    matchup: "Mexico City Capitanes",
    startDate: "2026-03-06",
    endDate: "2026-03-06",
    description: " on March 6, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "Oshkosh Arena",
    offerURL:
      "https://wisconsin.gleague.nba.com/2024-25-promotion-schedule?mkt_tok=MDQ1LUtSQS01OTgAAAGdRCMofuh8PrnuYD56uFkkTTuGA3SIbX4iSLOPTf_ML7zoWWCUAPekTvesmOMXwD8nSDvI-bYVzILUXU5A-gw",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "herd",
    eventName:
      "La Catrina Sugar Skull Bobblehead Part 2 of Set - 1st 1,000 Fans",
    rawName: "La Catrina Sugar Skull Bobblehead Part 2 of Set - 1st 1,000 Fans",
    matchup: "Mexico City Capitanes",
    startDate: "2026-03-07",
    endDate: "2026-03-07",
    description: " on March 7, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "Oshkosh Arena",
    offerURL:
      "https://wisconsin.gleague.nba.com/2024-25-promotion-schedule?mkt_tok=MDQ1LUtSQS01OTgAAAGdRCMofuh8PrnuYD56uFkkTTuGA3SIbX4iSLOPTf_ML7zoWWCUAPekTvesmOMXwD8nSDvI-bYVzILUXU5A-gw",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "herd",
    eventName: "AJ Green Bobblehead - 1st 1,000 Fans",
    rawName: "AJ Green Bobblehead - 1st 1,000 Fans",
    matchup: "Valley Suns",
    startDate: "2026-03-09",
    endDate: "2026-03-09",
    description: " on March 9, 2026 at 6:30 p.m.",
    timeAndZone: "6:30PM CST",
    location: "Oshkosh Arena",
    offerURL:
      "https://wisconsin.gleague.nba.com/2024-25-promotion-schedule?mkt_tok=MDQ1LUtSQS01OTgAAAGdRCMofuh8PrnuYD56uFkkTTuGA3SIbX4iSLOPTf_ML7zoWWCUAPekTvesmOMXwD8nSDvI-bYVzILUXU5A-gw",
    dayOfWeek: "monday",
  },

  {
    league: "gleaguenba",
    teamName: "herd",
    eventName: "Team Photo Poster Card - 1st 1,000 Fans",
    rawName: "Team Photo Poster Card - 1st 1,000 Fans",
    matchup: "College Park Skyhawks",
    startDate: "2026-03-23",
    endDate: "2026-03-23",
    description: " on March 23, 2026 at 6:00 p.m.",
    timeAndZone: "6:00PM CST",
    location: "Oshkosh Arena",
    offerURL:
      "https://wisconsin.gleague.nba.com/2024-25-promotion-schedule?mkt_tok=MDQ1LUtSQS01OTgAAAGdRCMofuh8PrnuYD56uFkkTTuGA3SIbX4iSLOPTf_ML7zoWWCUAPekTvesmOMXwD8nSDvI-bYVzILUXU5A-gw",
    dayOfWeek: "monday",
  },

  {
    league: "gleaguenba",
    teamName: "suns",
    eventName: "Valley Suns T-Shirt",
    rawName: "Valley Suns T-Shirt",
    matchup: "Rip City Remix",
    startDate: "2025-11-14",
    endDate: "2025-11-14",
    description: " on November 14, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM PST",
    location: "Mullett Arena",
    offerURL: "https://valley.gleague.nba.com/theme-nights",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "bulls",
    eventName: "Matas Buzelis Bobblehead",
    rawName: "Matas Buzelis Bobblehead",
    matchup: "Wisconsin Herd",
    startDate: "2025-11-08",
    endDate: "2025-11-08",
    description: " on November 8, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "Now Arena",
    offerURL:
      "https://windycity.gleague.nba.com/news/windy-city-bulls-announce-2025-26-promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "bulls",
    eventName: "Fleece Blanket",
    rawName: "Fleece Blanket",
    matchup: "Cleveland Charge",
    startDate: "2025-11-28",
    endDate: "2025-11-28",
    description: " on November 28, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "Now Arena",
    offerURL:
      "https://windycity.gleague.nba.com/news/windy-city-bulls-announce-2025-26-promotional-schedule",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "bulls",
    eventName: "Holiday-Themed Benny T.Bull Bobblehead ",
    rawName: "Holiday-Themed Benny T.Bull Bobblehead ",
    matchup: "Motor City Cruise",
    startDate: "2025-12-05",
    endDate: "2025-12-05",
    description: " on December 5, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "Now Arena",
    offerURL:
      "https://windycity.gleague.nba.com/news/windy-city-bulls-announce-2025-26-promotional-schedule",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "bulls",
    eventName: "Holiday-Themed Cousin Gus T.Bull Bobblehead ",
    rawName: "Holiday-Themed Cousin Gus T.Bull Bobblehead ",
    matchup: "Motor City Cruise",
    startDate: "2025-12-06",
    endDate: "2025-12-06",
    description: " on December 5, 2025 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "Now Arena",
    offerURL:
      "https://windycity.gleague.nba.com/news/windy-city-bulls-announce-2025-26-promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "bulls",
    eventName: "Gus T.Bull Rookie Bobblecard",
    rawName: "Gus T.Bull Rookie Bobblecard",
    matchup: "Osceola Magic",
    startDate: "2026-01-03",
    endDate: "2026-01-03",
    description: " on January 3, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "Now Arena",
    offerURL:
      "https://windycity.gleague.nba.com/news/windy-city-bulls-announce-2025-26-promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "bulls",
    eventName: "Space Jam Night - Youth Jersey",
    rawName: "Space Jam Night - Youth Jersey",
    matchup: "Delaware Blue Coats",
    startDate: "2026-01-10",
    endDate: "2026-01-10",
    description: " on January 10, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "Now Arena",
    offerURL:
      "https://windycity.gleague.nba.com/news/windy-city-bulls-announce-2025-26-promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "bulls",
    eventName: "Chicago Bulls Night- Stacey King Talking Bobblehead",
    rawName: "Chicago Bulls Night- Stacey King Talking Bobblehead",
    matchup: "Long Island Nets",
    startDate: "2026-02-06",
    endDate: "2026-02-06",
    description: " on February 6, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "Now Arena",
    offerURL:
      "https://windycity.gleague.nba.com/news/windy-city-bulls-announce-2025-26-promotional-schedule",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "bulls",
    eventName:
      "Greek Heritage Night; Gus. T Bulls Greek Statue Giveaway; Greek Rope Hat Ticket Offer",
    rawName:
      "Greek Heritage Night; Gus. T Bulls Greek Statue Giveaway; Greek Rope Hat Ticket Offer",
    matchup: "Raptors 905",
    startDate: "2026-02-20",
    endDate: "2026-02-20",
    description: " on February 20, 2026 at 6:30 p.m.",
    timeAndZone: "6:30PM CST",
    location: "Now Arena",
    offerURL:
      "https://windycity.gleague.nba.com/news/windy-city-bulls-announce-2025-26-promotional-schedule",
    dayOfWeek: "friday",
  },

  {
    league: "gleaguenba",
    teamName: "bulls",
    eventName:
      "Polish Heritage Night; Gus. T Bulls Global Bobblehead Giveaway; Polish Rope Hat Ticket Offer",
    rawName:
      "Polish Heritage Night; Gus. T Bulls Global Bobblehead Giveaway; Polish Rope Hat Ticket Offer",
    matchup: "Raptors 905",
    startDate: "2026-02-21",
    endDate: "2026-02-21",
    description: " on February 21, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "Now Arena",
    offerURL:
      "https://windycity.gleague.nba.com/news/windy-city-bulls-announce-2025-26-promotional-schedule",
    dayOfWeek: "saturday",
  },

  {
    league: "gleaguenba",
    teamName: "bulls",
    eventName: "Celebrate Chicago's Pope, Pope Leo XIV Booblehead",
    rawName: "Celebrate Chicago's Pope, Pope Leo XIV Booblehead",
    matchup: "Rio Grande Valley Vipers",
    startDate: "2026-03-08",
    endDate: "2026-03-08",
    description: " on March 8, 2026 at 1:00 p.m.",
    timeAndZone: "1:00PM CST",
    location: "Now Arena",
    offerURL:
      "https://windycity.gleague.nba.com/news/windy-city-bulls-announce-2025-26-promotional-schedule",
    dayOfWeek: "sunday",
  },

  {
    league: "gleaguenba",
    teamName: "bulls",
    eventName: "Los Toros Night: Mariachi Gus T. Bull Booblehead",
    rawName: "Los Toros Night: Mariachi Gus T. Bull Booblehead",
    matchup: "Valley Suns",
    startDate: "2026-03-12",
    endDate: "2026-03-12",
    description: " on March 12, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "Now Arena",
    offerURL:
      "https://windycity.gleague.nba.com/news/windy-city-bulls-announce-2025-26-promotional-schedule",
    dayOfWeek: "thursday",
  },

  {
    league: "gleaguenba",
    teamName: "bulls",
    eventName:
      "Filipino Heritage Night: Filipino Jersey Display Giveaway; Filipino Heritage Snap Bag Ticket Package",
    rawName:
      "Filipino Heritage Night: Filipino Jersey Display Giveaway; Filipino Heritage Snap Bag Ticket Package",
    matchup: "Valley Suns",
    startDate: "2026-03-14",
    endDate: "2026-03-14",
    description: " on March 14, 2026 at 7:00 p.m.",
    timeAndZone: "7:00PM CST",
    location: "Now Arena",
    offerURL:
      "https://windycity.gleague.nba.com/news/windy-city-bulls-announce-2025-26-promotional-schedule",
    dayOfWeek: "saturday",
  },
];

export default events;
