export const daysOfWeek = [
  "monday",
  "tuesday",
  "wednesday",
  "thursday",
  "friday",
  "saturday",
  "sunday",
];

export const capitalizedDOW = {
  monday: "Mondays",
  tuesday: "Tuesdays",
  wednesday: "Wednesdays",
  thursday: "Thursdays",
  friday: "Friday",
  saturday: "Saturdays",
  sunday: "Sundays",
};

export const monthNames = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const leagues = ["mlb", "nfl", "nhl", "nba"];

export const mlbTeams = [
  ["diamondbacks", "Arizona Diamondbacks"],
  ["braves", "Atlanta Braves"],
  ["orioles", "Baltimore Orioles"],
  ["redsox", "Boston Red Sox"],
  ["cubs", "Chicago Cubs"],
  ["whitesox", "Chicago White Sox"],
  ["reds", "Cincinnati Reds"],
  ["guardians", "Cleveland Guardians"],
  ["rockies", "Colorado Rockies"],
  ["tigers", "Detroit Tigers"],
  ["astros", "Houston Astros"],
  ["royals", "Kansas City Royals"],
  ["angels", "Los Angeles Angels"],
  ["dodgers", "Los Angeles Dodgers"],
  ["marlins", "Miami Marlins"],
  ["brewers", "Milwaukee Brewers"],
  ["twins", "Minnesota Twins"],
  ["mets", "New York Mets"],
  ["yankees", "New York Yankees"],
  ["athletics", "Oakland Athletics"],
  ["phillies", "Philadelphia Phillies"],
  ["pirates", "Pittsburgh Pirates"],
  ["padres", "San Diego Padres"],
  ["giants", "San Francisco Giants"],
  ["mariners", "Seattle Mariners"],
  ["cardinals", "St. Louis Cardinals"],
  ["rays", "Tampa Bay Rays"],
  ["rangers", "Texas Rangers"],
  ["bluejays", "Toronto Blue Jays"],
  ["nationals", "Washington Nationals"],
];

export const nflTeams = [
  ["cardinals", "Arizona Cardinals"],
  ["falcons", "Arizona Falcons"],
  ["ravens", "Baltimore Ravens"],
  ["bills", "Buffalo Bills"],
  ["panthers", "Carolina Panthers"],
  ["bears", "Chicago Bears"],
  ["bengals", "Cincinnati Bengals"],
  ["browns", "Cleveland Browns"],
  ["cowboys", "Dallas Cowboys"],
  ["broncos", "Denver Broncos"],
  ["lions", "Detroit Lions"],
  ["packers", "Green Bay Packers"],
  ["texans", "Houston Texans"],
  ["colts", "Indianapolis Colts"],
  ["jaguars", "Jacksonville Jaguars"],
  ["chiefs", "Kansas City Chiefs"],
  ["raiders", "Las Vegas Raiders"],
  ["chargers", "Los Angeles Chargers"],
  ["rams", "Los Angeles Rams"],
  ["dolphins", "Miami Dolphins"],
  ["vikings", "Minnesota Vikings"],
  ["patriots", "New England Patriots"],
  ["saints", "New Orleans Saints"],
  ["giants", "New York Giants"],
  ["jets", "New York Jets"],
  ["eagles", "Philadelphia Eagles"],
  ["steelers", "Pittsburgh Steelers"],
  ["49ers", "San Francisco 49ers"],
  ["seahawks", "Seattle Seahawks"],
  ["buccaneers", "Tampa Bay Buccaneers"],
  ["titans", "Tennessee Titans"],
  ["commanders", "Washington Commanders"],
];

export const nhlTeams = [
  ["ducks", "Anaheim Ducks"],
  ["coyotes", "Arizona Coyotes"],
  ["bruins", "Boston Bruins"],
  ["sabres", "Buffalo Sabres"],
  ["flames", "Calgary Flames"],
  ["hurricanes", "Carolina Hurricanes"],
  ["blackhawks", "Chicago Blackhawks"],
  ["avalanche", "Colorado Avalanche"],
  ["bluejackets", "Columbus Blue Jackets"],
  ["stars", "Dallas Stars"],
  ["redwings", "Detroit Red Wings"],
  ["oilers", "Edmonton Oilers"],
  ["panthers", "Florida Panthers"],
  ["kings", "Los Angeles Kings"],
  ["wild", "Minnesota Wild"],
  ["canadiens", "Montreal Canadiens"],
  ["predators", "Nashville Predators"],
  ["devils", "New Jersey Devils"],
  ["islanders", "New York Islanders"],
  ["rangers", "New York Rangers"],
  ["senators", "Ottawa Senators"],
  ["flyers", "Philadelphia Flyers"],
  ["penguins", "Pittsburgh Penguins"],
  ["sharks", "San Jose Sharks"],
  ["kraken", "Seattle Kraken"],
  ["blues", "St. Louis Blues"],
  ["lightning", "Tampa Bay Lightning"],
  ["mapleleafs", "Toronto Maple Leafs"],
  ["canucks", "Vancouver Canucks"],
  ["goldenknights", "Vegas Golden Knights"],
  ["capitals", "Washington Capitals"],
  ["jets", "Winnipeg Jets"],
];

export const nbaTeams = [
  ["hawks", "Atlanta Hawks"],
  ["celtics", "Boston Celtics"],
  ["nets", "Brooklyn Nets"],
  ["hornets", "Charlotte Hornets"],
  ["bulls", "Chicago Bulls"],
  ["cavaliers", "Cleveland Cavaliers"],
  ["mavericks", "Dallas Mavericks"],
  ["nuggets", "Denver Nuggets"],
  ["pistons", "Detroit Pistons"],
  ["warriors", "Golden State Warriors"],
  ["rockets", "Houston Rockets"],
  ["pacers", "Indiana Pacers"],
  ["clippers", "Los Angeles Clippers"],
  ["lakers", "Los Angeles Lakers"],
  ["grizzlies", "Memphis Grizzlies"],
  ["heat", "Miami Heat"],
  ["bucks", "Milwaukee Bucks"],
  ["timberwolves", "Minnesota Timberwolves"],
  ["pelicans", "New Orleans Pelicans"],
  ["knicks", "New York Knicks"],
  ["thunder", "Oklahoma City Thunder"],
  ["magic", "Orlando Magic"],
  ["76ers", "Philadelphia 76ers"],
  ["suns", "Phoenix Suns"],
  ["trailblazers", "Portland Trail Blazers"],
  ["kings", "Sacramento Kings"],
  ["spurs", "San Antonio Spurs"],
  ["raptors", "Toronto Raptors"],
  ["jazz", "Utah Jazz"],
  ["wizards", "Washington Wizards"],
];
