export const daysOfWeek = [
  "monday",
  "tuesday",
  "wednesday",
  "thursday",
  "friday",
  "saturday",
  "sunday",
];

export const capitalizedDOW = {
  monday: "Mondays",
  tuesday: "Tuesdays",
  wednesday: "Wednesdays",
  thursday: "Thursdays",
  friday: "Friday",
  saturday: "Saturdays",
  sunday: "Sundays",
};

export const monthNames = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const leagues = ["mlb", "nfl", "nba", "nhl", "ahl", "gleaguenba"];

export const mlbTeams = [
  ["angels", "Los Angeles Angels"],
  ["astros", "Houston Astros"],
  ["athletics", "Oakland Athletics"],
  ["bluejays", "Toronto Blue Jays"],
  ["braves", "Atlanta Braves"],
  ["brewers", "Milwaukee Brewers"],
  ["cardinals", "St. Louis Cardinals"],
  ["cubs", "Chicago Cubs"],
  ["diamondbacks", "Arizona Diamondbacks"],
  ["dodgers", "Los Angeles Dodgers"],
  ["giants", "San Francisco Giants"],
  ["guardians", "Cleveland Guardians"],
  ["mariners", "Seattle Mariners"],
  ["marlins", "Miami Marlins"],
  ["mets", "New York Mets"],
  ["nationals", "Washington Nationals"],
  ["orioles", "Baltimore Orioles"],
  ["padres", "San Diego Padres"],
  ["phillies", "Philadelphia Phillies"],
  ["pirates", "Pittsburgh Pirates"],
  ["rangers", "Texas Rangers"],
  ["rays", "Tampa Bay Rays"],
  ["reds", "Cincinnati Reds"],
  ["redsox", "Boston Red Sox"],
  ["rockies", "Colorado Rockies"],
  ["royals", "Kansas City Royals"],
  ["tigers", "Detroit Tigers"],
  ["twins", "Minnesota Twins"],
  ["whitesox", "Chicago White Sox"],
  ["yankees", "New York Yankees"],
];

export const nflTeams = [
  ["49ers", "San Francisco 49ers"],
  ["bears", "Chicago Bears"],
  ["bengals", "Cincinnati Bengals"],
  ["bills", "Buffalo Bills"],
  ["broncos", "Denver Broncos"],
  ["browns", "Cleveland Browns"],
  ["buccaneers", "Tampa Bay Buccaneers"],
  ["cardinals", "Arizona Cardinals"],
  ["chargers", "Los Angeles Chargers"],
  ["chiefs", "Kansas City Chiefs"],
  ["colts", "Indianapolis Colts"],
  ["commanders", "Washington Commanders"],
  ["cowboys", "Dallas Cowboys"],
  ["dolphins", "Miami Dolphins"],
  ["eagles", "Philadelphia Eagles"],
  ["falcons", "Arizona Falcons"],
  ["giants", "New York Giants"],
  ["jaguars", "Jacksonville Jaguars"],
  ["jets", "New York Jets"],
  ["lions", "Detroit Lions"],
  ["packers", "Green Bay Packers"],
  ["panthers", "Carolina Panthers"],
  ["patriots", "New England Patriots"],
  ["raiders", "Las Vegas Raiders"],
  ["rams", "Los Angeles Rams"],
  ["ravens", "Baltimore Ravens"],
  ["saints", "New Orleans Saints"],
  ["seahawks", "Seattle Seahawks"],
  ["steelers", "Pittsburgh Steelers"],
  ["texans", "Houston Texans"],
  ["titans", "Tennessee Titans"],
  ["vikings", "Minnesota Vikings"],
];

export const nhlTeams = [
  ["avalanche", "Colorado Avalanche"],
  ["blackhawks", "Chicago Blackhawks"],
  ["bluejackets", "Columbus Blue Jackets"],
  ["blues", "St. Louis Blues"],
  ["bruins", "Boston Bruins"],
  ["canadiens", "Montreal Canadiens"],
  ["canucks", "Vancouver Canucks"],
  ["capitals", "Washington Capitals"],
  ["coyotes", "Arizona Coyotes"],
  ["devils", "New Jersey Devils"],
  ["ducks", "Anaheim Ducks"],
  ["flames", "Calgary Flames"],
  ["flyers", "Philadelphia Flyers"],
  ["goldenknights", "Vegas Golden Knights"],
  ["hurricanes", "Carolina Hurricanes"],
  ["islanders", "New York Islanders"],
  ["jets", "Winnipeg Jets"],
  ["kings", "Los Angeles Kings"],
  ["kraken", "Seattle Kraken"],
  ["lightning", "Tampa Bay Lightning"],
  ["mapleleafs", "Toronto Maple Leafs"],
  ["oilers", "Edmonton Oilers"],
  ["panthers", "Florida Panthers"],
  ["penguins", "Pittsburgh Penguins"],
  ["predators", "Nashville Predators"],
  ["rangers", "New York Rangers"],
  ["redwings", "Detroit Red Wings"],
  ["sabres", "Buffalo Sabres"],
  ["senators", "Ottawa Senators"],
  ["sharks", "San Jose Sharks"],
  ["stars", "Dallas Stars"],
  ["wild", "Minnesota Wild"],
];

export const nbaTeams = [
  ["76ers", "Philadelphia 76ers"],
  ["bucks", "Milwaukee Bucks"],
  ["bulls", "Chicago Bulls"],
  ["cavaliers", "Cleveland Cavaliers"],
  ["celtics", "Boston Celtics"],
  ["clippers", "Los Angeles Clippers"],
  ["grizzlies", "Memphis Grizzlies"],
  ["hawks", "Atlanta Hawks"],
  ["heat", "Miami Heat"],
  ["hornets", "Charlotte Hornets"],
  ["jazz", "Utah Jazz"],
  ["kings", "Sacramento Kings"],
  ["knicks", "New York Knicks"],
  ["lakers", "Los Angeles Lakers"],
  ["magic", "Orlando Magic"],
  ["mavericks", "Dallas Mavericks"],
  ["nets", "Brooklyn Nets"],
  ["nuggets", "Denver Nuggets"],
  ["pacers", "Indiana Pacers"],
  ["pelicans", "New Orleans Pelicans"],
  ["pistons", "Detroit Pistons"],
  ["raptors", "Toronto Raptors"],
  ["rockets", "Houston Rockets"],
  ["spurs", "San Antonio Spurs"],
  ["suns", "Phoenix Suns"],
  ["thunder", "Oklahoma City Thunder"],
  ["timberwolves", "Minnesota Timberwolves"],
  ["trailblazers", "Portland Trail Blazers"],
  ["warriors", "Golden State Warriors"],
  ["wizards", "Washington Wizards"],
];

export const gleagueNbaTeams = [
  ["blue", "Oklahoma City Blue"],
  ["boom", "Noblesville Boom"],
  ["bulls", "Windy City Bulls"],
  ["capitanes", "Mexico City Capitanes"],
  ["celtics", "Maine Celtics"],
  ["charge", "Cleveland Charge"],
  ["clippers", "San Diego Clippers"],
  ["coats", "Delaware Blue Coats"],
  ["cruise", "Motor City Cruise"],
  ["go-go", "Capital City Go-Go"],
  ["gold", "Grand Rapids Gold"],
  ["herd", "Wisconsin Herd"],
  ["hustle", "Memphis Hustle"],
  ["kings", "Stockton Kings"],
  ["knicks", "Westchester Knicks"],
  ["lakers", "South Bay Lakers"],
  ["legends", "Texas Legends"],
  ["magic", "Osceola Magic"],
  ["nets", "Long Island Nets"],
  ["raptors", "Raptors 905"],
  ["remix", "Rip City Remix"],
  ["skyforce", "Sioux Falls Skyforce"],
  ["skyhawks", "College Park Skyhawks"],
  ["spurs", "Austin Spurs"],
  ["squadron", "Birmingham Squadron"],
  ["stars", "Salt Lake City Stars"],
  ["suns", "Valley Suns"],
  ["swarm", "Greensboro Swarm"],
  ["vipers", "Rio Grande Valley Vipers"],
  ["warriors", "Santa Cruz Warriors"],
  ["wolves", "Iowa Wolves"],
];

export const ahlTeams = [
  ["admirals", "Milwaukee Admirals"],
  ["americans", "Rochester Americans"],
  ["barracuda", "San Jose Barracuda"],
  ["bears", "Hershey Bears"],
  ["bruins", "Providence Bruins"],
  ["canucks", "Abbotsford Canucks"],
  ["checkers", "Charlotte Checkers"],
  ["comets", "Utica Comets"],
  ["condors", "Bakersfield Condors"],
  ["crunch", "Syracuse Crunch"],
  ["eagles", "Colorado Eagles"],
  ["firebrids", "Coachella Valley Firebirds"],
  ["griffins", "Grand Rapids Griffins"],
  ["gulls", "San Diego Gulls"],
  ["icehogs", "Rockford Icehogs"],
  ["islanders", "Bridgeport Islanders"],
  ["marlins", "Toronto Marlins"],
  ["monsters", "Cleveland Monsters"],
  ["moose", "Manitoba Moose"],
  ["penguins", "Scranton Penguins"],
  ["phantoms", "Lehigh Valley Phantoms"],
  ["regin", "Ontario Reign"], // needs to be changed to reign
  ["roadrunners", "Tucson Roadrunners"],
  ["rockets", "Laval Rockets"],
  ["senators", "Belleville Senators"],
  ["silverknights", "Henderson Silver Knights"],
  ["stars", "Texas Stars"],
  ["thunderbirds", "Springfield Thunderbirds"],
  ["wild", "Iowa Wild"],
  ["wolfpack", "Hartford Wolf Pack"],
  ["wolves", "Chicago Wolves"],
  ["wranglers", "Calgary Wranglers"],
];
