const nhlTeams = {
  ducks: {
    league: "nhl",
    url: "https://www.nhl.com/ducks/fans/promotional-schedule",
    giveawayList:
      "main section.nhl-l-section-bg div.nhl-l-section-bg__container.nhl-container section.d3-l-grid--outer.d3-l-section-row:nth-of-type(3)",
    giveawayListItem:
      ".d3-l-grid--inner article.nhl-c-promo-card-container .nhl-c-promo-card__content",
    giveawaylistItemLink: "a",
    alternativeEventLink: "https://www.nhl.com/ducks/fans/promotional-schedule",
    giveawaylistItemHeading: ".fa-text a h2.fa-text__title",
    // giveawaylistItemHeading: "div.fa-text__body p strong",
    giveawaylistItemDetails: "div.fa-text__body p",
    location: "Honda Center",
  },
  sabres: {
    league: "nhl",
    url: "https://www.nhl.com/sabres/tickets/theme-nights#schedule",
    giveawayList: ".nhl-l-section-bg__container.nhl-container",
    giveawayListItem:
      "section.d3-l-grid--outer.d3-l-section-row .d3-l-grid--inner.nhl-c-multi-column.items-3 .nhl-c-promo-card .nhl-c-promo-card__content",
    giveawaylistItemLink: "",
    alternativeEventLink:
      "https://www.nhl.com/sabres/tickets/theme-nights#schedule",
    giveawaylistItemHeading:
      ".nhl-c-promo-card__content .fa-text .fa-text__title",
    giveawaylistItemDetails:
      ".nhl-c-promo-card__content .fa-text .fa-text__body p",
    location: "KeyBank Center",
  },
  // blackhawks: {
  //   league: "nhl",
  //   url: "https://www.nhl.com/blackhawks/tickets/giveaways",
  //   giveawayList: "",
  //   giveawayListItem: "",
  //   giveawaylistItemLink: "",
  //   alternativeEventLink: "",
  //   giveawaylistItemHeading: "",
  //   giveawaylistItemDetails: "",
  //   location: "",
  // },
  // bluejackets: {
  //   league: "nhl",
  //   url: "https://www.nhl.com/bluejackets/tickets/promotional-calendar",
  //   giveawayList: "",
  //   giveawayListItem: "",
  //   giveawaylistItemLink: "",
  //   alternativeEventLink: "",
  //   giveawaylistItemHeading: "",
  //   giveawaylistItemDetails: "",
  //   location: "",
  // },
  // stars: {
  //   league: "nhl",
  //   url: "https://www.nhl.com/stars/tickets/promotional-schedule",
  //   giveawayList: "",
  //   giveawayListItem: "",
  //   giveawaylistItemLink: "",
  //   alternativeEventLink: "",
  //   giveawaylistItemHeading: "",
  //   giveawaylistItemDetails: "",
  //   location: "",
  // },
  // redwings: {
  //   league: "nhl",
  //   url: "https://www.nhl.com/redwings/tickets/promotions",
  //   giveawayList: "",
  //   giveawayListItem: "",
  //   giveawaylistItemLink: "",
  //   alternativeEventLink: "",
  //   giveawaylistItemHeading: "",
  //   giveawaylistItemDetails: "",
  //   location: "",
  // },
  // oilers: {
  //   league: "nhl",
  //   url: "https://www.nhl.com/oilers/tickets/promotional-games",
  //   giveawayList: "",
  //   giveawayListItem: "",
  //   giveawaylistItemLink: "",
  //   alternativeEventLink: "",
  //   giveawaylistItemHeading: "",
  //   giveawaylistItemDetails: "",
  //   location: "",
  // },
  // panthers: {
  //   league: "nhl",
  //   url: "https://www.nhl.com/panthers/tickets/theme-nights",
  //   giveawayList: "",
  //   giveawayListItem: "",
  //   giveawaylistItemLink: "",
  //   alternativeEventLink: "",
  //   giveawaylistItemHeading: "",
  //   giveawaylistItemDetails: "",
  //   location: "",
  // },
  // kings: {
  //   league: "nhl",
  //   url: "https://www.nhl.com/kings/news/kings-announce-key-promo-games-for-2025-26-season",
  //   giveawayList: "",
  //   giveawayListItem: "",
  //   giveawaylistItemLink: "",
  //   alternativeEventLink: "",
  //   giveawaylistItemHeading: "",
  //   giveawaylistItemDetails: "",
  //   location: "",
  // },
};

export default nhlTeams;
